### ISSUE TITLE
Review / Extend Unit Tests

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#108]

**Comment by devreal** [comment]
Created branch `sup-106-dart-doxygen` to work on the DART side of life...

**Comment by fmoessbauer** [comment]
By investigating #114 I noticed that many algorithms are not team aware. Especially whenever using global iterators, use `auto & team = iter.pattern().team()` and `team.barrier()` instead of `dash::barrier()`. See #126 for details.

**Comment by fuchsto** [comment]
@dash-project/developers Bump: Unit tests still could benefit from your reviews!
