### ISSUE TITLE
DARTLocalityTest.UnitLocality fails

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#11]
Hi Team!

the DARTLocalityTest.UnitLocality fails for `mpirun -n 2`. See [travis build #98](https://travis-ci.org/dash-project/dash/builds/167858979) for details.

```
[----------] run 2 out of 2 tests from DARTLocalityTest
[  ERROR   ] [UNIT 1] in /opt/dash/dash/test/DARTLocalityTest.cc:31
Expected: (ul->hwinfo.num_cores) > (0), actual: 0 vs 0
Unit 1
[  RUN     ] DARTLocalityTest.UnitLocality
[  FAILED  ] DARTLocalityTest.UnitLocality
```

Branch `bug-dart-locality`

**Comment by fuchsto** [comment]
Reason is that Travis is not a good match for our needs.
In the container, both MPI processes are mapped to the same physical core, confusing the locality discovery backend.
This is now tolerated in dart-impl/base/src/internal/domain_locality.c, but actually it's an invalid environment.
