### ISSUE TITLE
DART Interface (comm/globmem): redesign for data types

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#110]
Functions in the communication- and global memory modules use untyped communication buffers and memory ranges (`void *`).
This is problematic in several respects:

- communication is more efficient when the native underlying data type is known to MPI
- elements are not properly aligned in memory attached to MPI windows as the type displacement unit
   is currently set to `1`. This caused biblical pain recently.

Some communication primitives couldn't even work without specifying the data type.
I implemented those with a data type argument in the interface already, like:

~~~c
dart_ret_t dart_allreduce(
  void           * sendbuf,
  void           * recvbuf,
  size_t           nelem,
  dart_datatype_t  dtype,
  dart_operation_t op,
  dart_team_t      team);

dart_ret_t dart_accumulate(
  dart_gptr_t      gptr,
  void  *          values,
  size_t           nelem,
  dart_datatype_t  dtype,
  dart_operation_t op,
  dart_team_t      team);

dart_ret_t dart_fetch_and_op(
  dart_gptr_t      gptr,
  void *           value,
  void *           result,
  dart_datatype_t  dtype,
  dart_operation_t op,
  dart_team_t      team);
~~~

It's a significant interface change, but we definitely need to provide typed / generic interfaces for communication primitives and allocation. This has been decided over 6 months ago, actually.

Whether the current variants (untyped with `void *` and displacement 1) should be replaced our
kept in the interface in addition to their typed counterparts is not decided yet, but I see no
reason to keep the untyped versions.
If we should provide both, the untyped variants should be aliases for (`dtype:DART_BYTE`, `dspl:1`).

@fuerlinger @colinglass @jgraciahlrs @knuedd any objections?

**Comment by jgraciahlrs** [comment]
I agree, it makes little sense to have accumulate, etc, without a data type. The operation op is simply ill-defined.

**Comment by devreal** [comment]
I have been thinking about this issue as well. Do you have any pointers to back the claim that typed communication is more efficient?

> elements are not properly aligned in memory attached to MPI windows as the type displacement unit is currently set to 1. This caused biblical pain recently.

I'd be interested to hear the details :)

In general, I would not mind changing the API and dropping the non-typed versions as there are probably no codes relying on the current DART interface. Adding another parameter to the DART communication operations should not be too hard to implement.

**Comment by jgraciahlrs** [comment]
Regarding the data-types, I do not really think it matters for simple data types as MPI_FLOAT or MPI_BYTE. 

MPI is probably more efficient for derived data-types. The implementors of a particular MPI likely wrote better code for packing and unpacking derived data-types into buffers then the average MPI user would. I do not think that using simple MPI_FLOAT versus MPI_BYTE makes a difference. 

So, as long as we do not have a facility to define own data-types in DASH/DART, it is not really necessary to use anything else than MPI_BYTE at the lower level. Also, as far as I know, only MPI supports derive data-types, GASPI, etc, do not. This is a further argument against data-types at the dart level. 

Actually, some time ago, we were talking about Put/Get interfaces for strided data and similar.

**Comment by fuchsto** [comment]
As I wrote above, it is not about prettification in the interface, it's a technical necessity.

It produced (and probably still produces) bugs because alignment was off.
MPICH apparantly always aligns at 64 in `MPI_Alloc*`, OpenMPI2 doesn't. 
MPI_FLOAT vs. MPI_BYTE indeed didn't make much of a difference.
MPI_DOUBLE vs. MPI_BYTE, on the other hand, made much of a core dump, and only for specific
compiler optimizations. That is really horrible! 

Yes, I observed slight performance improvements in microbenchmarks for some MPI implementations when the correct data type has been used. Nothing I would write a song about, but well beyond noise threshold.
I should have the CSV dumps somewhere here ...

If GASPI does not support typed buffers (really?), this can be easily cared for with a macro or two.
Multiply `nelem` with size of user-specified data type and use `DART_BYTE`.

It's not like I was desperately longing for a hefty interface redesign, it's the pain that made me want it, and a Lovecraftian fear of the unknown.

EDIT: And even when disregarding all that: currently some functions use number of bytes, some expect number of elements (because their semantics require it, like accumulate).
And even disregarding that, too: any untyped allocation is a defect waiting to happen.

**Comment by fuchsto** [comment]
@dash-project/developers 

Let's find a final resolution for this. I think we all agree that DART should do its best to avoid incorrect behavior on higher layers.

For reference, the defect related to untyped buffers and its fix is documented in #39 
Have a look and let me know if I am mistaken in my conclusions.

Otherwise I will make all buffer-/value-related functions in DART depend on a data type argument.

**Comment by devreal** [comment]
I tried to find the fix but there are so many changes in #39, I can neither figure out the defect nor the fix in it.

Nevertheless, I think we should go for a typed interface. I'll be happy to take over the DART part, there surely will be significant changes required in DASH as well. 

:+1: from me.

**Comment by fuchsto** [comment]
@devreal I was referring to my last comment, way to the bottom. 
The fix is here:
https://github.com/dash-project/dash/pull/89/files#diff-c1d66a8de9d59875f81bcc797fd1d8f8R54

**Comment by fuchsto** [comment]
Further reference: (http://www.netlib.org/utk/papers/mpi-book/node36.html)

> If a value sent in a message is untyped (i.e., of type MPI_BYTE), MPI_BYTE MPI_BYTE then the binary 
> representation of the byte stored at the receiver is identical to the binary representation of the byte 
> loaded at the sender. This holds true, whether sender and receiver run in the same or in distinct 
> environments. No representation conversion is done. Note that representation conversion may occur 
> when values of type MPI_CHARACTER or MPI_CHAR are transferred, for example, from an EBCDIC 
> encoding to an ASCII encoding. MPI_CHARACTER MPI_CHAR

It is actually a coincidence that DART communication worked for Xeon Phi / Xeon.
