### ISSUE TITLE
dash::for_each only with const element access?

### ISSUE THREAD

**Issue by knuedd** [dash-project/dash#111]
dash::for_each only accepts a function with a "const ElementType&" argument. We want non-const access, too.

When using a std::for_each with "container.lbegin(), container.lend()" it works as expected. See https://github.com/dash-project/dash-apps/blob/master/dash_tutorial_2017-01/02-astro_load_image/astro-alternative.cpp#L238 for an example.

Cheers, Andreas

**Comment by fmoessbauer** [comment]
I think we need both signatures. This is not a bug, but just a missing feature.
I will implement that now.

**Comment by fmoessbauer** [comment]
Done in PR #112 . Btw: This is also a candidate for execution policies #104
