### ISSUE TITLE
Barriers are always team local only

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#114]
Currently it is not possible to use barriers which block all units if a team is split. Each barrier only blocks the units of the current team. See this example

```
auto & team = dash::Team::All();
auto & myteam = team.locality_split(dash::util::Locality::Scope::Core, 2);                                    if(myteam.dart_id() == 1){                                                       
  {                                                                              
      // Do somethings in team 1  
  }                                                                              
}
// does not work                                         
myteam.parent().barrier();
// does not work too
dash::Team::All().barrier();

  if(myteam.dart_id() == 2){                                                       
    // do something else after team 1 has finished                          
  } 
```

**Comment by fmoessbauer** [comment]
This bug is really strange. In branch `bug-114-team` the new team split unit tests work as expected. However almost the same case in `feat-hdf5-team` does not work.
And for debugging, keep in mind that the bug does not occur on CI, as there the team is not splitted.

For details see [HDF5ArrayTest](https://github.com/dash-project/dash/blob/feat-hdf5-team/dash/test/HDF5ArrayTest.cc#L415) and [TeamTest](https://github.com/dash-project/dash/blob/bug-114-team/dash/test/TeamTest.cc#L31)

**Comment by fuchsto** [comment]
Hm. Also, the question is what `Team::All()` should refer to. I think there is some specification missing.
Will get back to this soon.

**Comment by fuerlinger** [comment]
`dash::Team::All()` always refers to all units with which the program has been started.  `dash::Team::All().barrier()` is synonymous with `dash::barrier()` and should work as intended (barrier on all units) regardless of what sub-teams have been created.

**Comment by fuerlinger** [comment]
I have not tested with locality split, but with the simple regular split things work as expected:

```
  auto myid = dash::myid();

  auto& team = dash::Team::All();
  auto& myteam = team.split(2);

  if( myteam.position()==1 ) {
    cout << myid << " is member of team 1 (local id:"
     << myteam.myid() << ")"  << endl;
    sleep(1);
  }

  cout << myid << " before barrier"<< endl;
  myteam.parent().barrier();
  cout << myid << " after barrier"<< endl;
```

Note the usage of `position()` to distinguish the teams after the split. `position` might not be the best name,  we should probably rename it to either `rank()` or `id()` or something.

**Comment by fuchsto** [comment]
@fuerlinger Okay, that's what one would expect. We will extend unit tests for this then.
@fmoessbauer Does it depend on `locality_split` perhaps? The underlying mechanism for splitting is the same, though.

I suggest renaming `position()` to `relative_id`. The term _local_ is misleading because units in a child
team may be spread among non-local domains.
In the DART locality module, I use `id`. `global_id` and `relative_id`.

**Comment by fmoessbauer** [comment]
Ok, the team splits work properly. However, for locality_splits it is not guaranteed to get the requested number of teams (Bug #127).
The bug itself is a symptom of #125, #126 and #127

IMO the ticket can be closed.
