### ISSUE TITLE
DART header littered with DART_INTERFACE_* macros

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#119]
I found that the public DART header files all contain the macros DART_INTERFACE_ON and DART_INTERFACE_OFF. Upon closer investigation it seems that his has been used in the oneheader.pl script, which combines all DART interface header into one file. However, this does not seem to be used in the CMake based build system but is only called from within Makefiles in the DART directories. Is all of this still needed?

**Comment by fuerlinger** [comment]
Correct, it is used by the script which takes multiple header files and takes everything between the DART_INTERFACE_ON and DART_INTERFACE_OFF markers and puts it in one header file. 

It was never used as part of the build process but serves to create one single coherent header file that is the "official" DART API description. Please keep it in, it should not hurt much (there should be one ON and one OFF directive per file that delineates what is part of the official API.

**Comment by devreal** [comment]
You're right, it does not hurt. I just stumbled upon it while working on the documentation for the DART interface and wanted to make sure it's not legacy that is not needed anymore. Thanks for the clarification, will mark this issue as invalid.
