### ISSUE TITLE
DASH License

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#121]
DASH is currently released under a non-standard license.

We should decide on a FLOSS license like MIT, BSD, LGPL, ... as soon as possible as DASH is would
not comply to many classifications like CII.

For standards on FLOSS conforming licenses, see: https://opensource.org/licenses

As an example for FLOSS compliance, see requirements of the Core Infrastructure Initiative (CII): 
https://bestpractices.coreinfrastructure.org/projects/491

> The software MUST be released as FLOSS. [floss_license]
> 
> FLOSS is software released in a way that meets the Open Source Definition or
> Free Software Definition. \
> Examples of such licenses include the CC0, MIT, BSD 2-clause, BSD 3-clause revised,
> Apache 2.0, Lesser GNU General Public License (LGPL), and the GNU General Public License (GPL).
>
> For our purposes, this means that the license MUST be:
> 
> - an approved license by the Open Source Initiative (OSI), or
> - a free license as approved by the Free Software Foundation (FSF), or
> - a free license acceptable to Debian main, or
> - a "good" license according to Fedora.
> 
> The software MAY also be licensed other ways (e.g., "GPLv2 or proprietary" is acceptable).

**Comment by devreal** [comment]
Some examples to drive the discussion:

1. OpenMPI, MVAPICH, and OpenSHMEM use the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)
2. GASPI-GPI2 is lincesed under GPL-v3 (and proprietary)
3. HPX is licensed under the Boost Software License 1.0 (http://www.boost.org/users/license.html)

I agree with @fuchsto  that we need to decide on a license as soon as possible. Personally, I think the 3-clause BSD would be a good choice but maybe others have arguments for other licenses.

**Comment by fuchsto** [comment]
+1 for 3-clause BSD suggested by @devreal

**Comment by jgraciahlrs** [comment]
I am pretty sure we discussed and decided the licence already at a project meeting back in 2015 or early 2016. I am not sure which one we decided on. 

In any case, I favour BSD 3-clause.

**Comment by jgraciahlrs** [comment]
Sorry, reopening ;)

**Comment by fuchsto** [comment]
Changed in PR #337
