### ISSUE TITLE
DASH algorithms are not team aware

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#126]
Almost all DASH algorithms are not team aware because they use `dash::barrier()` internally. This has to be changed to team local barriers.

If using GlobIters, this can be done the following way:
`auto & team = iter.pattern().team()` and `team.barrier()` instead of `dash::barrier()`.

**Comment by fuchsto** [comment]
Well, this method chain

```
iter.pattern().team().barrier()
```

... is based on existing concepts already, so why not use it to extend the `GlobalIterator` concept by a method `barrier()` to synchronize all units in the team that have access to the iterator? It would always pick the correct team, too.

This would correspond to an atomic barrier (`dash::Atomic<T>.flush()|.barrier()`) in principle.
