### ISSUE TITLE
Locality splits might not split into requested number of teams

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#127]
If no locality information is available, `team.locality_split(..., n)` does not split the team.

IMO team splits should always return the requested number of teams. If no locality information is available, simple team splits (`team.split(n)`) should be used.

**Comment by fuchsto** [comment]
@fmoessbauer 
Hm, I don't aggree on this one.
Splitting is a request. If the programmer requested a locality split that is not possible, defaulting to "just any  split" is bad.

Likewise, what if there is only one unit in the team to split? There is no fallback for this.
Currently we raise an exception but that is not a sensible solution.

There should be a way to resolve the actual number of teams created in a split.

**Comment by fuchsto** [comment]
@fuerlinger @fmoessbauer @devreal 

See branch `feat-127-nsplit`:

- Added output parameter `nout` to `dart_group_split`, `dart_group_locality_split` returning number of actual groups created in the split.
- Added `dash::Team.num_siblings()` returning the number of groups created in the split of the parent team

Use case: 

~~~c++
// request split into 8 groups:
auto & child_team = dash::Team::All().split(8);
// actual number of groups created (assuming 4 units in total):
auto num_split = child_team.num_siblings(); // -> 4
assert(child_team.position() < num_split);
~~~

**Comment by fmoessbauer** [comment]
I agree that this is a better solution than enforcing the number of teams.
