### ISSUE TITLE
Proper definition of local and global unit id's in GlobMem

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#136]
Currently it is not clear, which methods in `GlobMem.h` require team local id's and which require global id's.
This has lead to various bugs in the past, including an erroneous fix in PR #133.

Therefor I propose to rename the interface the following way:
- `relative_unit_id` for team local id's
- `global_unit_id` for id's related to `dash::Team::All()`

This should also be fixed in documentation.

**Comment by fuchsto** [comment]
Discussed in #143

**Comment by fmoessbauer** [comment]
As discussed in #143, types will be introduced to fix this. Hence I close this duplicate.
