### ISSUE TITLE
Improvements to DART communication interface

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#138]
While reviewing the changes for #110 I realized that there are some inconsistencies in the DART communication interface:

1. We are mixing `int` and `size_t` for arguments describing the number of elements in a provided buffer, e.g., in dart_allgatherv. They should all be the same, preferably `size_t`. The same data type should be used for displacements to be coherent. Note that in some places this would require a conversion, e.g., `dart_allgatherv`
2. If we use `size_t` as per 1), we might get into situations where an overflow happens when passing the number of elements to MPI since the MPI interface uses `int` for size-related arguments. In parts, the implementation already checks for these overflows, e.g., in `dart_get`. This should be extended to all communication operations.  
3. We currently do not consider constness in the interface. I propose adding the `const` keyword to all relevant pointer arguments, e.g., in `dart_put`. 
4. `dart_bcast` does not support datatypes as requested in #110. 
5. The implementation of `dart_reduce` is missing and the interface definition is broken. 
6. The standard `dart_get` and `dart_put` operations are still data-type agnostic whereas `dart_get_handle` accepts the data-type as arguments. This needs to be unified. 

I will start implementing these fixes unless there are any objections.

**Comment by fuerlinger** [comment]
Sounds good to me!

**Comment by devreal** [comment]
Going through the code, I found this gem in `dart_accumulate`:
```
dart_ret_t dart_accumulate(
  dart_gptr_t      gptr,
  void  *          values,
  size_t           nelem,
  dart_datatype_t  dtype,
  dart_operation_t op,
  dart_team_t      team)
{
  // ...
  (void)(team); // To prevent compiler warning from unused parameter.
  // ...
}
```

Any reason the team argument was introduced earlier? Any reason to keep it?
