### ISSUE TITLE
Execute all test suites in single, isolated runs of dash-test

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#146]
Currently, if a test leads to a broken or undefined state of the DASH runtime, subsequent tests may fail and thus report false positives.

Add a script that allows to perform tests as isolated runs of single test suites.

**Comment by fuchsto** [comment]
Created branch `sup-146-test-isolated`

**Comment by devreal** [comment]
Thanks a lot for this, will try it today.

**Comment by devreal** [comment]
Tried it. Unfortunately, the script fails on our cluster due to the `-k` parameter not being supported by `timeout` in versions < 8.5, see http://git.savannah.gnu.org/cgit/coreutils.git/tree/NEWS#n1626. Is the additional kill really necessary?

**Comment by fuchsto** [comment]
@devreal 
The kill-switch (no pun intended) was just for additional stability. Didn't know the option is non-standard.
