### ISSUE TITLE
DART Group Allocation/Initialization

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#167]
I am not too happy with the allocation/initialization interface of DART groups. ATM, a group has to be allocated as follows:

```
  dart_group_t *  group;
  size_t size;
  dart_group_sizeof(&size);
  group = static_cast<dart_group_t *>(malloc(size));
  dart_group_init(group),
```

It requires 3 (in words: three!) function calls to setup a group. This is rather complicated and highly error-prone. I understand that we cannot expose the implementation of a `dart_group_t` since it depends on the underlying implementation (shmem, mpi, ...). However, I'd like to propose a simpler interface:

```
dart_ret_t dart_group_init(dart_group_t **group);
```

which would allocate the implementation-specific group data object and initialize it. 

On another thought, it might even be worth changing the type of a group from

```
typedef struct dart_group_struct dart_group_t;
```

to 

```
typedef struct dart_group_struct* dart_group_t;
```

That way, a `dart_group_t` can be used like a `dart_unit_t` or `dart_team_t` and does not have to think about the fact that the size of `struct dart_group_struct` is unknown. It is only important that a group has to be initialized before it's use.

**Comment by fuerlinger** [comment]
@devreal Yes, this was a snafu in the early days of coming up with the specification for DART. I'm all in favor of a redesign along those lines (including changing the type of dart_group_t).

**Comment by fuchsto** [comment]
@devreal @fuerlinger 
I agree that defining allocation and initialization as inseparable operation is a a good thing because this prevents the creation of `dart_group_t` objects in an invalid state.

My only objection is that `dart_group_t` would be a native pointer in your variant, and this would be hidden from the user.
So when a user would try to use, for example, `dart_put` to send a DART group, this would lead to unintended behavior as a native pointer is sent that cannot be used at the target.

**Comment by fuchsto** [comment]
More important, @devreal addresses an issue that is actually of more general concern for DART.
Currently there is no uniform object-oriented style to construct, clone, assign and destruct instances of DART types.

I suggest the following vocabulary for all DART types:

- `dart_foo_create(dart_foo_t ** obj)`
  constructor (allocation + default initialization)
- `dart_foo_assign(dart_foo_t * lhs, dart_foo_t * rhs)` \
  assignment with respective ownership semantics (`lhs` is destroyed and releases allocated resources)
- `dart_foo_clone(dart_foo_t * obj, dart_foo_t ** clone)` \
   deep-copy: `obj` allocates own resources
- `dart_foo_delete(dart_foo_t * obj)` \
  destructor

Note that there is no `dart_foo_copy` as it would not imply ownership semantics and does not prevent shared ownership.

**Comment by devreal** [comment]
> So when a user would try to use, for example, dart_put to send a DART group, this would lead to unintended behavior as a native pointer is sent that cannot be used at the target.

Is this a valid use-case? My understanding is that groups are local to units and each unit should construct it's own groups. In the current MPI implementation, copying a team is illegal anyway because the underlying MPI group cannot be copied. 

> I suggest the following vocabulary for all DART types:
> [...]

This sounds like a huge overhead to me, which for most types is not required. `dart_unit_t` and `dart_team_t` are integral types that do not have to be initialized that way. `dart_group_t` is rather special and I doubt that we should implement the full blown set of functions just because we have one outlier.

**Comment by devreal** [comment]
I should note that my second proposed change (making `dart_group_t` a pointer typedef) would come with changes to all group functions to fit to the use of the other DART datatypes, i.e., strip the pointer from all function definitions:

```
dart_ret_t dart_group_copy(const dart_group_t *gin,
                           dart_group_t *gout);
```

would become

```
dart_ret_t dart_group_copy(const dart_group_t gin,
                           dart_group_t gout);
```

If we only implement the first proposed the interface would remain stable except for two changes to the API (deletion of `dart_group_sizeof` and adaptation of `dart_group_init` or renaming to `dart_group_create`).

**Comment by fuchsto** [comment]
@devreal 
Ah, no, my wording was unclear there: I don't suggest to introduce these OO-methods for *all* DART types.
Just for those that

- involve ownership
- already have some kind of `create` and `destroy` functions already defined

So this would only affect `dart_team_t` and the locality types, I think.

There is no `dart_team_assign` or `dart_team_clone`, yet.
However, these have been suggested by @fuerlinger already.

**Comment by devreal** [comment]
I'm all in for common naming in DART, so :+1: from my side. I guess you meant `dart_group_t` instead of `dart_team_t` though ;)

**Comment by fuchsto** [comment]
@devreal 
Ok, will create a branch for that for everyone to review.

I was indeed referring to `dart_team_t`. There is `dart_team_create` and `dart_team_destroy` but no `dart_team_clone`, yet (suggested by @fuerlinger in #125)

**Comment by devreal** [comment]
Got it, I already started massaging the DART group interface in branch `feat-167-groupalloc` can move that to yours as well.
