### ISSUE TITLE
Migrate User Guide to dash/doc

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#17]
The DASH user guide, currently written in Latex in the dash-papers/userguide repository, should be migrated to the DASH distribution documentation in Markdown format.

I migrated the NArray section for starters.

The user guide now is automatically generated from dash/doc on readthedocs:
https://dash.readthedocs.io/en/latest

**Comment by fmoessbauer** [comment]
I ported my part of the guide to dash/docs.

However: Wouldn't it be better to put the documentation in it's own repository? Otherwise each figure inflates the dash repository.

**Comment by fuchsto** [comment]
The documentation is part of the DASH distribution, so that's fine.
Figures should be SVG files, not binaries.
