### ISSUE TITLE
A* Implementation

### ISSUE THREAD

**Issue by Golim4r** [dash-project/dash#171]

**Comment by fuerlinger** [comment]
If it is more than a few dozen lines of code, the A* search implementation for DASH should probably live in the [dash-apps repository](https://github.com/dash-project/dash-apps).

**Comment by fuchsto** [comment]
@fuerlinger Yes, right. My bad, I was thinking about integrating it in tests and Doxygen, but it's actually a stand-alone application at this point.
@Golim4r I will explain how to add a DASH application in a mail tomorrow
