### ISSUE TITLE
A build script just for tests.

### ISSUE THREAD

**Issue by clemensmanert** [dash-project/dash#173]
As a developer I want to have a build script which just builds specified tests.

**Comment by fuchsto** [comment]
@clemensmanert 
That's already available, isn't it? See CMake option `TESTCASES`.

Example:

~~~bash
cmake .. -DTESTCASES="Array*,Matrix*"
~~~

Build scripts for testing depend on specific use cases. If developers need a build script for a set of tests, they should modify a private copy of the existing scripts.

Private build scripts should be named `my.something` so they are automatically ignored by git.

**Comment by clemensmanert** [comment]
I want to have a script which builds a minimal config of dash with specified unit tests. The script could also run the specified ones then automatically.

**Comment by fuchsto** [comment]
Create a private copy of `build.minimal.sh` and specify `-DTESTCASES`, we don't need to deliver a specific build script for that.
