### ISSUE TITLE
Setup one DASH run per Testgroup in CI

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#185]
Initialize DASH in setup of each test group and finalize DASH after each test group. This requires changes in TestPrinter, as this currently uses `dash::shared` to gather results.

After this implementation, change CI to run all tests in a single run.

```
MPI_Init()

dash::init()
// Testgroup 1
dash::finalize()

dash::init()
// Testgroup 2
dash::finalize()
[...]

MPI_Finalize()
```

**Comment by fuchsto** [comment]
Merged your changes, now trying CI runs with single test run.

**Comment by fmoessbauer** [comment]
Looks good but unfortunately some XML Files are still corrupted. I will give it a second try tomorrow.

**Comment by fuchsto** [comment]
@fmoessbauer 
Currently, when I run

~~~
$ mpirun -n 3 ./bin/dash-test-mpi 
~~~

... no test cases are run. Why is that?

**Comment by fmoessbauer** [comment]
I cannot reproduce this on CI nor Projekt03. Maybe you have set GTEST_FILTER? Where did you test?
The last missing task of this ticket (overlapping in XML files) ist fixed in #188 

For me the output looks at follows (on project 03)
```
mpirun -n 3 bin/dash-test-mpi
...
[==========] 151 tests from 41 test cases ran. (23923 ms total)
[  PASSED  ] 151 tests passed
```

**Comment by fuchsto** [comment]
Ah, yes, that's possible.

Still, we should use a common base class for test suites instead of copy-pasting setup and teardown in every test suite.
See PR #170

**Comment by fmoessbauer** [comment]
Hi, I definitively agree on that. Also the solution with the global `TESTENV` is not so pretty.
With your test class, we can simply sed over the `test/*.h` files and replace the `dash::init` and `dash::finalize` commands with the appropriate setup and teardown calls.

I will implement the necessary changes after PR #143 is merged, as otherwise we will get conflicts in many places.

**Comment by fuchsto** [comment]
Also, a timeout for single test suites would be useful.

When running test suites in isolation with `dash-test-all-single.sh`, a frozen test case does not break the following tests.
We should try to maintain this with the new test base class.

**Comment by fmoessbauer** [comment]
Theoretically you are right, but if a test hangs, this is in almost any case due to a hanging MPI statement. So practically even a timeout does not help as we start only one process instead of one process per group.

**Comment by fuchsto** [comment]
Yes, hm, you're right of course, it's not a trivial problem.
We would need a timer thread that cancels the MPI runtime to break deadlocks, and I don't even know if that's feasible. MPI is not exactly renowned for rich fault tolerance / recovery features.

Just forget about it. And apart from that, let's just keep each other from wasting any more time than desperately necessary in CI for now.
