### ISSUE TITLE
Use pragma once as header guard

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#208]
While preparing fixes for #206, Clang reported a mismatching header guard (see https://github.com/dash-project/dash/pull/207/commits/3776bfe0b2f1aa87b969107b9c3693c63aa7030f). Is there any reason not to replace the `#define` based header guards with `pragma once`? They are much cleaner and less verbose. All compilers we use should support this pragma (including Cray).

**Comment by fuchsto** [comment]
It has its advantages, but unfortunately `#pragma once` is non-standard.
We could use it in addition to include guards, though.
The actual missing feature is running cpplint and/or CppCheck in integration tests. These would report mismatched and malformed include guards.

If we should switch to `#pragma once` entirely (without additional include guards), the build must at least include a preprocessor check that yields a meaningful error message à la "Prepocessor must support #pragma once".

See:
- https://en.wikipedia.org/wiki/Pragma_once
- https://sourceforge.net/p/predef/wiki/Compilers/
