### ISSUE TITLE
Refactoring / Cleanup in dash::Team

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#211]
During debugging of PR #210 @devreal detected various design or implementation adversities. These are currently marked with TODO @fuchsto and should be fixed in the near future.

Original comment by @devreal 

> The way we currently use `dash::Team::_team_[null|all]` is dangerous since in several places they are passed as reference to the caller, i.e., `TeamLocality::team()`, who is then able to alter these teams. Of course, the user should not be able to alter these invariants! Fixing this is not easy, since pointers to Teams are used in several places. Ideally, these invariants would be `constexpr`, which is hard to do with the current implementation of the ctor...

**Comment by devreal** [comment]
Having given this another thought and checking the code, I realized that the user cannot change a `dash::Team` after its creation except for splitting it, which completely legal on dash::Team::All(). Thus, he cannot break anything. 

However, in many cases where pointers to dash::Team are used we can easily use references iff the team is guaranteed to be initialized in the ctor and never changed through any operation on the object containing the reference. This relieves the check for `nullptr` in these cases.

**Comment by devreal** [comment]
OK, never mind. Using references does not work if we use assignment operators, delayed allocation, and the like. Marking this bug as invalid...
