### ISSUE TITLE
MPI_Group_free() called after MPI_FINALIZE

### ISSUE THREAD

**Issue by BenjaProg** [dash-project/dash#238]
In my simple program for learning how to work with teams in DASH [here](http://doc.dash-project.org/Examples/TeamExperimentationTemplate) I get the output you can see in the attachment.
But the error(s) only occurs in my VM if the block in line 90-91 is a comment.
So if the whole program is executed I get the error(s).

I assume it's a bug in Team::split(), but perhaps I am wrong?
[errOut.txt](https://github.com/dash-project/dash/files/716782/errOut.txt)

**Comment by devreal** [comment]
This is not directly a bug in `Team::split` but related: in `Team::split` the new team is registered for later deallocation. The deallocation then happens upon destruction of the static `dash::Team::All()`, which happens after `dash::finalize` has been called. A simple solution would be to not delete any children in `~Team` after DASH has been finalized. Alternatively, `dash::finalize` should make sure that the teams are properly deallocated, which is the preferable way imo.

**Comment by devreal** [comment]
I think this is easy to fix, provide a fix soon. Thanks for reporting.

**Comment by BenjaProg** [comment]
okay cool thanks!

**Comment by devreal** [comment]
Can you please check the branch `bug-238-teamfinalize` to see whether that fixes your issue? I could not immediately reproduce the error message on my local machine.

**Comment by BenjaProg** [comment]
Yeah I am on it!
I were suprised by the error later, at first it never occured but if it occured once, it occured every time 
(that was yesterday). And today same again, for hours no error and with the first occurance i couldn't get rid of it.

**Comment by BenjaProg** [comment]
Hm now I get a Segmentation Fault, see attachment
[errOut2.txt](https://github.com/dash-project/dash/files/717070/errOut2.txt)

By the way I run it with 4 units, if good to know...

**Comment by fuchsto** [comment]
Fixed in #244
