### ISSUE TITLE
Segfault with dash::Array using CSR-Pattern and odd number of units

### ISSUE THREAD

**Issue by BenjaProg** [dash-project/dash#256]
Hey @dash-project/developers ,
There is some strange behaviour with my test scenario (main.cpp).
[CSRBug.zip](https://github.com/dash-project/dash/files/734924/CSRBug.zip)

I get a segmentation fault if I execute the test with an odd number of units and at least three.
In the loop lines 42-45 is where the segmentation fault happens.
Unfortunately I and @ddiefenthaler couldn't track it further down until now.
(Note: this fault hasn't occured on ddiefenthaler's machine.)

If I enabled the count variable and(!) the cout in the loop the fault is prevented (at my machine...).
So If there is a segfault, the line `DASH_LOG_DEBUG( "Message:     ", "made it." );`
isn't reached anymore.

The variant_x.txt files hold some of the output possibilites on my machine. 
With variant_1 and variant_3 not all processes did return and i had to send a interrupt signal.

Thanks for your help in advance!

**Comment by devreal** [comment]
Can you please provide us with a stack trace of the Segfault? If you run locally you can do something like:

```
mpirun -n 3 xterm -e gdb --args ./a.out <parameter>
```

**Comment by BenjaProg** [comment]
okay i will provide it this afternoon, unfortunately i am on my way to university every moment

**Comment by rkowalewski** [comment]
And please provide your build settings: Which compiler, which libraries, etc.

**Comment by fuchsto** [comment]
> So If there is a segfault, the line DASH_LOG_DEBUG( "Message: ", "made it." );
isn't reached anymore.

You don't know, at least not from missing output. The log operation might have been completed but a subsequent segfault prevented the flush of `std::clog`.

**Comment by BenjaProg** [comment]
sorry for the delay, I gladly provide you with a stack trace but I first have to work into gdb more.
@rkowalewski: hope the attached info from the build script hold all relevant infos ;-)
[additional Information_1.txt](https://github.com/dash-project/dash/files/736187/additional.Information_1.txt)

**Comment by BenjaProg** [comment]
That's the backtrace I got.
I am sorry for the screenshot! Is there a way to pipe the output of gdb in a file? 
Because copy/paste wasn't possible.
![gdb overview](https://cloud.githubusercontent.com/assets/20214726/22461206/9f36f39a-e7a8-11e6-865c-c394d9ed2ee0.PNG)

**Comment by devreal** [comment]
I just gave it a try with current development and cannot reproduce the issue locally. I used 1.10.2, GCC 5.4.1 and 3 processes. Also tried with 5 processes, still succeeded. Missing something?

**Comment by BenjaProg** [comment]
@devreal Probably not, it seems the error only appears on my local vm :/ 
"1.10.2" is the version number of what?
I will have a closer look this weekend.

**Comment by devreal** [comment]
Ahh sorry, yes. I meant OpenMPI 1.10.2, which is the version that comes packaged with my system.

**Comment by fuchsto** [comment]
@BenjaProg You could test local sizes before assigning values. Are values in `local_sizes[myid]` identical to `array.lend() - array.lbegin()`?

**Comment by BenjaProg** [comment]
There is now a dedicated branch for this [bug](https://github.com/dash-project/dash/tree/bug-256-csrpattern). A CSRPatternTest is already there and `array.lend() - array.lbegin()` is being checked as well, but hasn't been a problem so far.

**Comment by fuchsto** [comment]
The actual defect is in allocation in DART, see #280 and `CSRPatternTest` in #279
