### ISSUE TITLE
Call of a constant function within a non-constant function

### ISSUE THREAD

**Issue by Fettpet** [dash-project/dash#259]
In the functions [const_mapped_type_reference at(const key_type & key) const](https://github.com/dash-project/dash/blob/development/dash/include/dash/map/UnorderedMap.h#L513)
 and
 [const_mapped_type_reference at(const key_type & key) const](https://github.com/dash-project/dash/blob/development/dash/include/dash/map/UnorderedMapLocalRef.h#L232)
the operator[] is called. The operator[] has no const overload.

**Comment by fuchsto** [comment]
The actual defect is that `at(const key_type & key) const` is implemented using `operator[](key)`.

Just as for `std::unordered_map`, there is no const overload for `operator[](key)` as it would create an element with the specified key if it doesn't exist yet:

<http://en.cppreference.com/w/cpp/container/unordered_map/operator_at>

**Comment by fuchsto** [comment]
Fixed in #262
