### ISSUE TITLE
Portable Dash Version

### ISSUE THREAD

**Issue by Fettpet** [dash-project/dash#265]
The current version of dash use the compiler flags  "-march=native -mtune=native". These are hidden in the sub-CMake files [config/coreglitch.cmake ](https://github.com/dash-project/dash/blob/development/config/coreglitch.cmake#L12) and [config/default.cmake](https://github.com/dash-project/dash/blob/development/config/default.cmake#L8). Without editing these files it is not possible to build a portable dash version. It would be nice if there is a cmake flag to enable a cross compiled version. 
At the moment it is pretty hard to see, that dash is build for a specific hardware. Even in ccmake there isn't a hint.

**Comment by fuchsto** [comment]
I agree and suggest `BUILD_SHARED_LIBS` as the corresponding build option.

**Comment by devreal** [comment]
@fuchsto You still might want to have `-march=native` optimized shared libraries. Building shared libs and optimizing for a specific target architecture are independent aspects imo. You can already pass  `BUILD_SHARED_LIBS` to CMake. I rather suggest a flag such as `BUILD_GENERIC` to disable target-specific optimizations.

**Comment by fuchsto** [comment]
Ah, you are right of course. So let's introduce both. I would follow the build options provided by MPICH and standard tools like PAPI and hwloc.

**Comment by fuchsto** [comment]
... oh, I wasn't aware of this cmake option. I will use an `.so` build in some CI scenario then, we should check that this actually works for DART/DASH.

**Comment by devreal** [comment]
I've been using shared libs in one of my branches and haven't had any issue with it so far (as far as I can remember ^^). It's good to have it in CI though.
