### ISSUE TITLE
UnorderedMapGlobIter const local function

### ISSUE THREAD

**Issue by Fettpet** [dash-project/dash#266]
Within [ const_reference operator*() const](https://github.com/dash-project/dash/blob/development/dash/include/dash/map/UnorderedMapGlobIter.h#L259) in the UnorderedMapGlobIter the function local() is called. But the const version of the [local function](https://github.com/dash-project/dash/blob/development/dash/include/dash/map/UnorderedMapGlobIter.h#L305) is within a comment.

**Comment by fuchsto** [comment]
Addressed in PR #276
