### ISSUE TITLE
Passing a unit to GlobMem::lbegin?

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#269]
I've been scrolling through the `GlobMem` code and found two things noteworthy:

1. There are basically two overloads for `lbegin` and `lend`, each. One takes no arguments and returns the begin of the local memory on the current unit. But what is the other supposed to return? The local pointer on an arbitrary (remote) unit? Any reason to expose this to the user? While it seems like a source of error it also has another flaw: the underlying `dart_gptr_getaddr` returns `NULL` for any unit that is not the current unit. 

2. Since `lbegin` and `lend` do not modify the current `GlobMem` instance it should be safe to keep just the `const` version of these functions and throw away the non-`const` versions to reduce code duplication. Any reason for keeping the non-`const` versions?

**Comment by devreal** [comment]
Ahh, stupid me! The separate `const` versions are required because they have `const` and non-`const` return types. 

I realized the the `lend` and `lbegin` methods taking a unit ID are used to initialize the members `_lbegin` and `_lend` in the c'tor. I think they should not be public though.

**Comment by fuchsto** [comment]
Exactly, I'm not too sure if these are actually required in the public interface anyways.
I will put some thought into it and report back.

**Comment by fuchsto** [comment]
Update: The overloads of `lbegin`, `lend` accepting a global unit id should be private, they are only required in the constructor of `GlobMem` and only return valid results if the passed unit id is the active unit.
