### ISSUE TITLE
Defect detected via NastMPI in MatrixTest.UnderfilledLocalViewSpec

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#277]
Test failed for 3 units.
Build details:

<https://circleci.com/gh/dash-project/dash/1202>

@fmoessbauer Might be related to recent changes of underfilled block arithmetic in pattern code?

**Comment by fmoessbauer** [comment]
This seems to be not a problem of the local view, but anywere below in DART. I tried to track down the bug, but without valgrind I was not able to find it. I guess that we try to access memory which has not been allocated by dart, but I cannot prove that.

@rkowalewski please have a look the bug. I did enhance the unit test in branch `bug-227-localview`

**Comment by fuchsto** [comment]
Marked as duplicate: This is another effect of the defect reported in #280 

Only occurs for odd number of units and unaligned local memory.
