### ISSUE TITLE
Local memory allocated by DART is not aligned

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#280]
A test case of CSRPattern showed that local memory of arrays allocated by DART is not aligned.
This leads to segfaults and undefined behavior in several situations, apparently when the compiler uses automatic loop parallelization.

See test case `CSRPatternTest.InitArray` in #279 for details.
Using `value_t = int` works, with `size_t` the test segfaults for GCC 5.4 and OpenMPI.

When loop parallelization is prevented (e.g. by a log event in the loop), the test passes.
A similar issue has previously been noted for `dash::min_element` where explicit alignment has been used to prevent segfaults.

<https://github.com/dash-project/dash/issues/39#issuecomment-260107154>
<https://github.com/dash-project/dash/issues/110#issuecomment-260915655>

This also caused the defect reported in #277 

The defect is not related to the CSR pattern. In this use case, all units allocate the same local capacity.

**Comment by BenjaProg** [comment]
I just built dash with `-O0` (release & debug) and the segfault doesn't occur anymore! 👍 
But I still wonder, why is there a segfault only with odd numbers of units (>1)? 
And why is it only with OpenMPI?

**Comment by fuchsto** [comment]
@BenjaProg For an even number of units, alignment happens to be a multiple of `sizeof(size_t)`. This is just a coincidence. You can verify this from the logged result of `array.lbegin() % 64`.

```
2 units: reinterpret_cast<size_t>(array.lbegin()) % 64: 40 (= 5 * sizeof(size_t) - works)
3 units: reinterpret_cast<size_t>(array.lbegin()) % 64:  4 (no multiple of sizeof(size_t) - SEGV)
4 units: reinterpret_cast<size_t>(array.lbegin()) % 64: 32 (= 4 * sizeof(size_t) - works)
5 units: reinterpret_cast<size_t>(array.lbegin()) % 64: 60 (no multiple of sizeof(size_t) - SEGV)
6 units: reinterpret_cast<size_t>(array.lbegin()) % 64: 24 (= 3 * sizeof(size_t) - works)
7 units: reinterpret_cast<size_t>(array.lbegin()) % 64: 52 (no multiple of sizeof(size_t) - SEGV)
```

I have no idea how OpenMPI affects this, though.
We don't have to know, anyways: Memory allocated by DART must be at least cache-aligned!

**Comment by fuchsto** [comment]
I found the related defect in `dash::min_element` and its fix, I already suggested aligned allocation back then:

<https://github.com/dash-project/dash/issues/39#issuecomment-260107154>
<https://github.com/dash-project/dash/issues/110#issuecomment-260915655>

Now, thank god allocation functions in DART have been extended to data types, right ... ? :P

**Comment by BenjaProg** [comment]
@fuchsto **Thanks for finding this very sturdy bug! And thank you very much for the explanation! :-)**

It's somehow obvious but I confirmed it anyway:
DASH can be compiled with -O3 -Ofast and so on but the program/test have to be compiled with -O0 right now. Thought it would be nice to know if someone wants to try out. 
_The entire library must **not** be recompiled!_ ;-)

**Comment by fuchsto** [comment]
That's plausible, the presumably-parellelized loop is in the test code.
But this doesn't help much, local memory must be at least cache-aligned.
Actually it should be cache- and data size aligned, just like `new[]` in C++.

**Comment by devreal** [comment]
I'm investigating this. In the example, the memory is allocated through `dart_team_memalloc_aligned` (no pun intended, I guess), which passes on the memory allocated by `MPI_Win_allocate_shared`. The allocation is marked as `alloc_shared_noncontig` and the provided displacement unit is passed to MPI. I had assumed that this causes MPI to allocate aligned memory.

@fuchsto Are you sure that C++ `new[]` returns cache-aligned memory? At http://en.cppreference.com/w/cpp/memory/new/operator_new it reads:

> This function is required to return a pointer suitably aligned to hold an object of any fundamental alignment.


Also see: http://en.cppreference.com/w/cpp/types/max_align_t

> std::max_align_t is a POD type whose alignment requirement is at least as strict (as large) as that of every scalar type. 

Sounds to me like `sizeof(size_t)`, which is not necessarily cache-aligned.

**Comment by fuchsto** [comment]
@devreal Thank you for your quick response, I followed your bug branch on this.
Yes, `new` aligns for data size for PODs only, apparently. 32 for AVX as suggested in your branch should work. I'm on the bus and will have a cup of standardese on this.
User-defined composite types like `struct { int; char; double; }` have to be padded in user code, but that's rather unsurprising.

**Comment by devreal** [comment]
After some more experiments I found that the problem only seems to appear with `MPI_Win_allocate_shared`, which is used if shared memory windows are enabled. If they are disabled, `MPI_Alloc_mem` is used, which seems to return addresses with acceptable (aka `sizeof(size_t)`) alignments. This holds true for both OpenMPI 1.10.5 and 2.0.2 but not for MPICH 3.2. I will file a report against OpenMPI for this issue. 

AFAICS, trying to recover alignment from what OpenMPI gives us will be messy but I will look into that as well.

**Comment by devreal** [comment]
I sent the report to the OpenMPI user mailing list together with a reproducer, will keep you posted. For the time being, the easiest fix would be to disable shared memory windows if OpenMPI is used. 

@fuchsto Not wanting to nit-pick here but your example is perfectly fine and does not need padding as the compiler aligns the `double` member to 8-byte ;) `sizeof` this struct should be 16 byte (unless it's `packed`). It's different if you have `struct { double; int; char; }`, which has no internal padding and thus size 13.

**Comment by fuchsto** [comment]
Yes! I was referring to the latter. My mental auto-correct seems to prevent making up unaligned structs ;)

**Comment by fuchsto** [comment]
Still, I would like DART to support user-specified alignments à la `std::memalign`, that is: aligning within MPI-allocated memory as you suggested. But that's not a bug, obviously.

So, all in all: another job well done thanks to a splendid team effort that would have not been necessary if OpenMPI ... archh ... well ...

**Comment by devreal** [comment]
Yep, thanks to all of you for putting your effort into investigating this! :+1: I'm glad though that I am not the only OpenMPI user around here ^^

Having something like `dart_memalign` should be straight-forward and does not require any additional book-keeping. Enforcing a certain (user-defined?) alignment in `dart_team_memalloc_aligned` should not be too hard but requires some modifications in the segment meta data, which I would like to post-pone until #221 is done to avoid conflicts. Defaulting to 32 Byte would be possible as well if we agree on that.

**Comment by fuchsto** [comment]
Yes, let's get back to the actual challenges.

... what a weird, nasty bug.

**Comment by devreal** [comment]
That was quick! There is a patch, which has already been merged: https://github.com/open-mpi/ompi/pull/2978

It seems that the alignment is now consistently 8-byte no matter the number of processes (which should be fine for our use-case). I noticed though that on my machine `malloc` (which is probably used by `MPI_Alloc_mem`) consistently aligns on 16-byte boarders.

```
[malloc] Alignment of baseptr=0x1e40bd0: 16
[malloc] Alignment of baseptr=0x13c1c00: 0
[malloc] Alignment of baseptr=0x2760b50: 16
[MPI_Alloc_mem] Alignment of baseptr=0x13c1690: 16
[MPI_Alloc_mem] Alignment of baseptr=0x1e40660: 32
[MPI_Alloc_mem] Alignment of baseptr=0x27605e0: 32
[MPI_Win_allocate] Alignment of baseptr=0x7f7a09193108: 8
[MPI_Win_allocate] Alignment of baseptr=0x7f6a54787108: 8
[MPI_Win_allocate] Alignment of baseptr=0x7fcd9f8bf108: 8
[MPI_Win_allocate_shared] Alignment of baseptr=0x7fcd9f8bf108: 8
[MPI_Win_allocate_shared] Alignment of baseptr=0x7f6a54787108: 8
[MPI_Win_allocate_shared] Alignment of baseptr=0x7f7a09193108: 8
```

So I guess custom alignment is necessary :( Should we introduce a new (defaulted) parameter to `dart_team_memalloc_aligned` or go with a new function? The default would be 0, which implies no explicit alignment.

**Comment by fuchsto** [comment]
C-style malloc is not cache aligned, I have some custom alignment utils in algorithms like `min_element`.
Well, with an alignment parameter, we would now definitely have a clash in the naming scheme :)

Can imagine the documentation already. "Alignment does not refer to aligned local allocation, but aligned global allocation, which is not related to data alignment, but only memory alignment, which is not cache-aligned, but also might.", or something like that (gnihi!).

How about `dart_team_coalloc`?

**Comment by devreal** [comment]
> How about `dart_team_coalloc`?

You are right, the name clash would be rather confusing. I seem to remember having seen this proposal in another context but just cannot find it right now. For me at least, the term `coalloc` does not have specific semantics but I cannot come up with something better. How about `balanced`? In any case, we can pass the information of `same_size` global allocations to MPI for some potential optimizations so having this guarantee would be valuable.

**Comment by fuchsto** [comment]
Ah, of course, "balanced" is perfectly right

(I can't object to this, it's in my own freakn paper).

**Comment by fuerlinger** [comment]
Or, "symmetric", for which there is precedent, for example the symmetric heap in OpenSHMEM, but yes, we should get rid of "aligned".

http://www.ibm.com/support/knowledgecenter/en/SSFK3V_1.3.0/com.ibm.cluster.protocols.v1r3.pp300.doc/bl511_shmalloc.htm

**Comment by devreal** [comment]
:+1: for `symmetric` from my side.

**Comment by BenjaProg** [comment]
Should the alignment be identical on each unit? Than "symmetric" implied it best to me 👍

**Comment by fuchsto** [comment]
Closing this issue as the defect is fixed, Discussed feature request for aligned allocation is continued in #297
