### ISSUE TITLE
Support PAPI versions greater 5.4.1

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#29]
Currently it is not possible to compile DASH with a PAPI version > 5.4.1. The problem cannot be easily fixed, as functions from `string.h` and `papi.h` clash.

```
In file included from /usr/include/c++/5/cstring:42:0,
                 from /opt/dash/dash/include/dash/internal/StreamConversion.h:14,
                 from /opt/dash/dash/include/dash/internal/Logging.h:5,
                 from /opt/dash/dash/include/dash/util/Timer.h:20,
                 from /opt/dash/dash/src/util/Timer.cc:1:
/usr/include/string.h:525:40: error: declaration of 'int ffsll(long long int) throw ()' has a different exception specifier
      __THROW __attribute__ ((__const__));
                                        ^
In file included from /opt/dash/dash/include/dash/util/internal/TimestampPAPI.h:9:0,
                 from /opt/dash/dash/include/dash/util/Timer.h:14,
                 from /opt/dash/dash/src/util/Timer.cc:1:
/opt/papi/include/papi.h:1024:8: error: from previous declaration 'int ffsll(long long int)'
    int ffsll(long long lli); //required for --with-ffsll and used in extras.c/papi.c
```

**Comment by fuchsto** [comment]
This is a bug in PAPI, not DASH, actually. I wrote a patch for PAPI that I currently use to build PAPI manually.

**Comment by devreal** [comment]
Just tried with PAPI 5.5.0 and the problem seems to persist. Could you please send the patch to the PAPI mailing list? Or send me the patch and I will be happy to forward it :)

**Comment by fuchsto** [comment]
Just retried with papi-5.5.1, had no issues when removing configure flag `--with-ffsll`.
Pushed to branch `sup-29-papi` for testing.

**Comment by fuchsto** [comment]
@fmoessbauer CI passed with new container configuration.
Please review and close if this is resolved now.

**Comment by fuchsto** [comment]
Eh, my bad, this only fixes the build when PAPI is installed from source, but still fails if it has been installed from a package or container.

PAPI build fails when compiling with `-pedantic`. They don't use strict compile flags themselves, apparently.

Will submit a request to the PAPI mailing list.

**Comment by devreal** [comment]
Now using 5.5.1
