### ISSUE TITLE
Fix dereference of nullptr in locality module

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#301]
In [UnitLocality.h](https://github.com/dash-project/dash/blob/b6c58b5bdc2ffbff52b5c60ce9079fc146618965/dash/include/dash/util/UnitLocality.h#L133-L137), 137 a nullptr is dereferenced.

**Comment by fuchsto** [comment]
Yes. 😰

**Comment by fuchsto** [comment]
Fixed in PR #302
