### ISSUE TITLE
Implement Allocator Traits

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#303]
The goal is to have allocator traits to automatically check if the allocator and the pattern are comatible.

**Comment by rkowalewski** [comment]
We should clarify this because it is not completely clear to me what you mean. Probably you want to avoid static patterns / containers with the dynamic memory allocator? If yes I agree, however, there is is some kind of misconception IMO as patterns and allocators deal with orthogonal aspects.

**Comment by fuchsto** [comment]
We discussed this last Friday, I will write a brief article on this.

**Comment by rkowalewski** [comment]
Fine, then let's talk about this tomorrow

**Comment by fuchsto** [comment]
For tracking: https://github.com/dash-project/dash/pull/310

**Comment by devreal** [comment]
Resolved through #310.
