### ISSUE TITLE
Improvements to DART Buddy Allocator

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#307]
Problems identified by @fuchsto in #306:

> The dart_buddy_alloc interface is dubios in general.
> https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_mem.c#L128
> 
> So in the C source, the signature is size_t dart_buddy_alloc(...) but the implementation returns -1 on error (without a cast to indicate that this is intentional).
> 
> Then, failure of dart_buddy_alloc is tested accordingly:
> https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_globmem.c#L159
> 
> Semantically, dart_buddy_alloc is supposed to return an offset:
> https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_mem.c#L141
> 
> ... and offsets are signed. Always. It's the law.
> 
> Oh, and there also is dart_buddy_new, for good measure:
> https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_mem.c#L58
> 
> It doesn't do any harm at the moment, but feel free to clean up the interface.

I guess, this kind of mess is what happens when you blindly copy code from some Chinese dude... To put it with the words of the 45th president: I inherited a mess.

**Comment by fuchsto** [comment]
We will make the buddy-allocator clean again, and we will make StackOverflow pay for it.
