### ISSUE TITLE
Evaluate interprocedural (icc) / link-time (gcc) optimization

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#31]
Add compiler / linker flags and evaluate benchmark results (`dash/examples/bench.*`):
- gcc: `-lto`
- icc: `-qipo` or `-ipo` depending on version

**Comment by fmoessbauer** [comment]
Currently only icc is able to link DASH with link time optimization. When enabled the benchmark results are slightly better. See [here](https://github.com/dash-project/dash-benchmarking/tree/lto-comparison) for a comparison. Fortunately there is no noticable impact on the compile time.

If using gcc with `-flto`, the binaries cannot be linked. Hence I disabled `lto` if the compiler is gnu.

```
Linking CXX executable app.01.mindeg.mpi
/tmp/cczl7r4s.ltrans0.ltrans.o: In function `void test_array_alloc<int>(unsigned long)':
<artificial>:(.text+0x27): undefined reference to `dash::myid()'
<artificial>:(.text+0x35): undefined reference to `dash::size()'
<artificial>:(.text+0x3d): undefined reference to `dash::size()'
...
```

Changes are made in branch `feat-link-time-opt`

**Comment by fmoessbauer** [comment]
Some research showed that the linking problem is a bug in GCC's linker plugin. If disabling the plugin compilation and linking work as expected.

However this feature seems experimental to me as sometimes internal compiler errors appear. (GCC 5.3.0)

**Comment by fmoessbauer** [comment]
Using gcc 5.3.0 (on projekt03) the benchmark results are slightly worse for the LTO case. Hence I do not recommend to enable LTO per default.

Therefor I added a build flag `ENABLE_LT_OPTIMIZATION` to enable or disable LTO in release builds (as LTO is not compatible with debug mode). Per default the flag is disabled.
