### ISSUE TITLE
Problems with MPI_Rget

### ISSUE THREAD

**Issue by stiefn** [dash-project/dash#350]
MPI_Get has been recently exchanged with MPI_Rget in dart_get_blocking().
This seems to not be working on my local machine: The call to MPI_Rget blocks and never finishes. 
Changing MPI_Rget back to MPI_Get makes everything work as expected again.

My local MPI version: OpenMPI 2.0.1

**Comment by stiefn** [comment]
To reproduce my test, the following program can be run with the latest DASH version from the branch feat-graph, using 2 nodes:

```
#include <libdash.h>
#include <iostream>

struct vprop {
  int id;
};

struct eprop {
  int id;
};

typedef dash::Graph<dash::DirectedGraph, void, vprop, eprop> graph_t;

int main(int argc, char* argv[]) {
  dash::init(&argc, &argv);
  graph_t g(10);
  for(int i = 0; i < 6; ++i) {
    vprop prop { 2 * i + dash::myid() };
    g.add_vertex(prop);
  }
  g.barrier();

  if(dash::myid() == 0) {
    std::cout << g.test()._properties.id << std::endl;
  }
}
```

The test() method will try to get a value from unit 1.

**Comment by devreal** [comment]
Thanks for the report. Can you please post a MWE that works on `development`?

**Comment by stiefn** [comment]
Yes, of course. Sorry for that.

```
#include <libdash.h>
#include <iostream>

int main(int argc, char* argv[]) {
  dash::init(&argc, &argv);
  dash::Team & team = dash::Team::All();
  std::vector<int> v { 1, 2 };
  dart_gptr_t gptr      = DART_GPTR_NULL;
  dart_storage_t ds = dash::dart_storage<int>(2);
  dart_team_memregister(team.dart_id(), ds.nelem, ds.dtype, v.data(), &gptr);
  if(dash::myid() == 0) {
    dart_gptr_setunit(&gptr, dash::team_unit_t(1));
    int test;
    dart_storage_t ds2 = dash::dart_storage<int>(1);
    dart_get_blocking(static_cast<void*>(&test), gptr, ds2.nelem, ds2.dtype)
    std::cout << test << std::endl;
  }
  dash::barrier();

  return 0;
}
```

Also, here is the code block for dart_get_blocking, that makes it work again:
```
  DART_LOG_DEBUG("dart_get_blocking: MPI_Get");
  if (MPI_Get(dest,
              nelem,
              mpi_dtype,
              team_unit_id.id,
              offset,
              nelem,
              mpi_dtype,
              win)
      != MPI_SUCCESS) {
    DART_LOG_ERROR("dart_get_blocking ! MPI_Get failed");
    return DART_ERR_INVAL;
  }
  DART_LOG_DEBUG("dart_get_blocking: MPI_Win_flush");
  if (MPI_Win_flush(team_unit_id.id, win) != MPI_SUCCESS) {
    DART_LOG_ERROR("dart_get_blocking ! MPI_Win_flush failed");
    return DART_ERR_INVAL;
  }
```

If you have problems reproducing the error, I can send you my VM image.

**Comment by rkowalewski** [comment]
I would recommend to use a newer ompi version (either 2.1.0 or nightly) because they have various problems regarding one-sided communication in v2.0.1.

See [#2538](https://github.com/open-mpi/ompi/issues/2538) and [#2530](https://github.com/open-mpi/ompi/issues/2530) for example.

**Comment by devreal** [comment]
Thanks a lot for the MWE. I can confirm the hang with OpenMPI 2.0.1. With v2.1.0 things seemed to have improved, your example works there. 

Also, it seems that 1.10.* is not affected either. I think is is an OpenMPI issue (which seems solved on their side).

**Comment by stiefn** [comment]
OK great, thanks for the heads up!

**Comment by ddiefenthaler** [comment]
Seems related to issue #63.
