### ISSUE TITLE
Maximal width of dash::is_atomic_compatible types

### ISSUE THREAD

**Issue by ddiefenthaler** [dash-project/dash#355]
Currently the trait `dash::is_atomic_compatible` matches the size of the type against `std::size_t` to determine if atomic access is possible (Defined in [Types.h](https://github.com/dash-project/dash/blob/1978c10151d7fb000ecc3bd6e50099fd3835256e/dash/include/dash/Types.h#L235)).
This was introduced and already shortly discussed in pull request #338.

Is `std::size_t` really the correct type to match against?
I tried to look up the maximal supported width of an atomic operation
and found the extension **Double-wide compare-and-swap** in the wikipedia entry to [Compare-and-swap](https://en.wikipedia.org/wiki/Compare-and-swap#Extensions).
It looks like atomic operation on twice the width of `std::size_t` are possible.

Or is this a limitation of the _One-Sided Communication_ in MPI?
Otherwise `uintmax_t` might be a more appropriate type to check against.

This questions arises as in one test a `dash::Atomic<double>` is used which breaks in my 32 bit VM.

**Comment by fuchsto** [comment]
Indeed, `CMPXCHG16B`, if available, should be wider than `size_t`. But MPI does not support DWCAS so it would only work for local operations.
That's why I suggested `is_global_atomic_compatible` and `is_local_atomic_compatible` somewhere in the comments.

**Comment by fmoessbauer** [comment]
But can’t we use the minimum of MPI and local for the meantime? Or do 32-Bit MPI implementations at max support 32-bit types for atomic operations? Anyway, our current implementation has to be refactored, as an atomic operation semantically is not limited by any type length (as I mentioned earlier, you know…).

**Comment by ddiefenthaler** [comment]
I guess the supported width for MPI is `std::size_t` then, so how it currently is should be fine.
Even though in dart it seems to just match against `DART_TYPE_LONGLONG`: [dart_communication.c](https://github.com/dash-project/dash/blob/1978c10151d7fb000ecc3bd6e50099fd3835256e/dart-impl/mpi/src/dart_communication.c#L440)
Actually it is quite hard to find a good documentation about what MPI supports and how it differs on a 32-bit machine.

Currently there seem to be two checks for type length/data type, so semantically it should already be fine:
- one at runtime in the mentioned DART-file.
- another one at compile time in DASH (introduced by the mentioned PR #338): [Atomic.h](https://github.com/dash-project/dash/blob/1978c10151d7fb000ecc3bd6e50099fd3835256e/dash/include/dash/Atomic.h#L51-L53)

To get back to the original problem why I asked,
currently in the test [`UnorderdMapTest.MappedAtomics`](https://github.com/dash-project/dash/blob/development/dash/test/container/UnorderedMapTest.cc#L472) a `dash::Atomic<double>` is used which breaks through the `static_assert`on 32-bit machines.
Would a `dash::Atomic<float>` be sufficient in this test case, or should this be solved with some kind a `#ifdef` / C++ type system trick?

**Comment by devreal** [comment]
Technically, the atomic DART functions (with the documented exception of `dart_compare_and_swap`, which you referenced) support all DART data types. Afaik, the MPI standard does not limit the size of the type that used in atomic operations (again, with the notable exception of `MPI_Compare_and_swap`). I'm not sure how they are implemented on 32 bit machines but it would be interesting to test (I have none at hand right now and won't get around to installing one in the next 2 weeks). 

There is a type `MPI_LONG_DOUBLE`, which we could mirror as `DART_TYPE_LONG_DOUBLE`. 

The documentation for `dart_compare_and_swap`: https://github.com/dash-project/dash/blob/development/dart-if/include/dash/dart/if/dart_communication.h#L298

**Comment by fuchsto** [comment]
@fmoessbauer Yes, atomic operations are, in formal principle, independent from the data type and microinstruction support, that's no news and you are still missing my point, Wisenheimer 😋 
For global operations only DART data types are supported as of now because `GlobRef<Atomic>` does not provide locking mechanisms to support arbitrary type sizes.
So again, that's why I suggested `is_local_atomic_*` vs. `is_global_atomic_*` as locking mechanisms are provided locally via `std::atomic`. If this deviation from the general definition of atomic operations bugs you as much as it bugs me, implement locking fallbacks for `GlobRef<Atomic>`.
