### ISSUE TITLE
Include minimal build configuration in CI tests

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#36]
Motivated by issue #34, standard build configurations (Release, Debug) x Minimal should be covered by integration test.

**Comment by fmoessbauer** [comment]
Implemented in PR #59.

**Comment by fuchsto** [comment]
This issue should be closed. Defects coming up in the minimal build are reported in a bug issue.

**Comment by fuchsto** [comment]
Re-testing minimal build in CI, see branch `sup-70-ci-minimal`.
