### ISSUE TITLE
Fix Copy / Move / Rule of five of Matrix

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#368]
Copy and move semantics are currently broken on (at least) `dash::Matrix`. This is due to the missing ctors and assignment operators.

**Comment by fuchsto** [comment]
They are not broken, they are deleted. A `dash::Matrix` may not be copied as it's a typically huge object. Moving should work, though.

**Comment by fuchsto** [comment]
Your changes in #369 look okay in this respect, though. Just don't implement assignment and copy ;)

**Comment by fmoessbauer** [comment]
They were missing... Anyway, of course copy is deleted, but move should be perfectly well. I guess we have to fix that on other places in dash as well. I just stumbled upon this by making my `dash::Coarray` fulfill the container concept ;)

**Comment by fmoessbauer** [comment]
Fixed in #369
