### ISSUE TITLE
Errors while running tests in development branch

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#370]
I got the following errors for tests in development:
Desktop machine (4 cores)
openmpi: 1.10.6
gcc 6.3.1

enabled:
shared_windows, unified_memory_model, hwloc,libnuma

- 4 ranks  (shared_wondows, libnuma and hwloc disabled)

  [  FAILED  ] 1 tests, listed below
  [  FAILED  ] DARTLockTest.TeamLockUnlock
- 5 ranks
  [  ERROR   ] [UNIT 4] in /home/huenich/zih/projects/DASH/github/dash/dash/test/container MatrixTest.cc:1093
  Expected: (corner[0] + matrix.local.extent(0)) <= (h), actual: 8 vs 7
  Unit 4
  and
    FAILED  ] MatrixTest.UnderfilledBlockedPatternExtents
  [  ERROR   ] [UNIT 0] in /home/huenich/zih/projects/DASH/github/dash_dev/dash/test/TestPrinter.h:145  
  Failed
- 6 ranks:
  kind of undefined behavior
  All passed or 

  [  FAILED  ] 1 tests, listed below
  [  FAILED  ] AtomicTest.AtomicInterface

  or

  MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD 
  with errorcode -6.
 
  NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
  You may or may not see output from other processes, depending on
  exactly when Open MPI kills them.
  --------------------------------------------------------------------------
  [    5 ERROR ] [ 26736 ] domain_locality.c        :517  !!! DART: Assertion failed: domain->num_units >     unit_idx
  [    0 ERROR ] [ 26728 ] domain_locality.c        :517  !!! DART: Assertion failed: domain->num_units > unit_idx

**Comment by rkowalewski** [comment]
It looks like the identical issue in #230.

@dhinf Can you please check if starting your tests like the following still results in an error:

~~~bash
mpirun --map-by core -n [NPROCS] ./app
~~~

**Comment by dhinf** [comment]
--map-by core solved it for 6 cores but now 4 cores in this setup is buggy

**Comment by rkowalewski** [comment]
OK these are actually multiple independent issues. The others do not really refer to the locality stuff and need separate inspection.

**Comment by dhinf** [comment]
ok nope, with 6 cores i still get (sometimes)
ERROR   ] [UNIT 0] in /home/huenich/zih/projects/DASH/github/dash_dev/dash/test/types/AtomicTest.cc:403
      Expected: array[3].load()
      Which is: 3
To be equal to: 1
Unit 0

[  FAILED  ] 1 tests, listed below
[  FAILED  ] AtomicTest.AtomicInterface


with 8 ranks the locality errors sill appears

Has locality a problem with oversubscripting?

I test it on my Desktop machine (4 cores).

**Comment by devreal** [comment]
I cannot reproduce the error in `DARTLockTest.TeamLockUnlock` on my machine. What error do you see?

**Comment by dhinf** [comment]
4 Ranks and only unified_memory_model enabled

[ERROR   ] [UNIT 2] in /home/huenich/zih/projects/DASH/github/dash_dev/dash/test/dart/DARTLockTest.cc:230
      Expected: num_iterations * team.size()
      Which is: 20
To be equal to: static_cast<value_t>(shared.get())
      Which is: -150688948
Unit 2
[=  2 LOG =]               TestBase.h : 264 | -==- Test case finished at unit 2 
[  ERROR   ] [UNIT 3] in /home/huenich/zih/projects/DASH/github/dash_dev/dash/test/dart/DARTLockTest.cc:230
      Expected: num_iterations * team.size()
      Which is: 20
To be equal to: static_cast<value_t>(shared.get())
      Which is: -150688948
Unit 3

**Comment by devreal** [comment]
Thanks, looking at the code it makes sense: the `team` was not used correctly to set the initial value. I committed a hotfix, please try again on current `development`.

**Comment by dhinf** [comment]
This one is solved :)

**Comment by devreal** [comment]
There was a `barrier` missing in `AtomicTest.AtomicInterface`. I just pushed a hotfix, please check that as well.

**Comment by dhinf** [comment]
also solved. 
The reason for the locality errors is maybe the oversubscripting.
