### ISSUE TITLE
DART Mutex hangs for > 16 units

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#372]
The DART mutex seems to hang if using more than 16 units (projekt03, single node, 24 cores). Surprisingly with 15 units it works as expected. The executed test is [`CoArrayTest.Mutex`](https://github.com/dash-project/dash/blob/feat-coarray/dash/test/container/CoArrayTest.cc#L298), but the test hangs in the first part, which just uses the `dash::Mutex`.

At least on projekt03 the bug is perfectly reproducible.

As the bug might depend on the environment, attached are the build log and a run with every possible kind of logging enabled.

` mpirun -n 16 --map-by core build/bin/dash-test-mpi 1> CoArray-Mutex.output.log 2> CoArray-Mutex.error.log`

[CoArray-Mutex.output.txt](https://github.com/dash-project/dash/files/959080/CoArray-Mutex.output.txt)
[CoArray-Mutex.error.txt](https://github.com/dash-project/dash/files/959081/CoArray-Mutex.error.txt)
[build.txt](https://github.com/dash-project/dash/files/959082/build.txt)

**Comment by devreal** [comment]
Ain't nobody gonna need more than 15 processes...

Just in case anyone ever does: From a quick glimpse at the log, it looks like it could be a progress issue (see #361): unit 0 is polling on a local value using MPI atomics without any remote data access. However, I cannot reproduce it locally. I added an `MPI_Iprobe` while waiting for the local next pointer in your branch, just to see if that is sufficient. Will get back to it tomorrow.

**Comment by fuchsto** [comment]
Seconded, I think there is a world market for maybe five processes.

**Comment by devreal** [comment]
I ran the test suite from `development` yesterday on our cluster on 64 processes (8proc x 8nodes) and did not see `dash::Mutex` deadlock a single time. @fmoessbauer did you have a chance to see whether the added `MPI_Iprobe` helped?

**Comment by fmoessbauer** [comment]
Hi, thanks for the fix. That solved the problem 👍 These progress issues become quite annoying.
