### ISSUE TITLE
Arithmetic operator overloading in LocalMatrixRef

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#381]
In LocalMatrixRef the arithmetic operators are declared but only + and += are defined. And the defined ones don't work properly. 

I suggest to remove them, like in MatrixRef.

**Comment by fmoessbauer** [comment]
After having a short glance at the code I think this has to be refactored anyway. The specialization of the bottom case (Dim = 0) is not necessary and should be removed.
Instead, for the last dimension local references `T &`  should be returned. This was also wrong in [`MatrixRef.h`](https://github.com/dash-project/dash/blob/development/dash/include/dash/matrix/MatrixRef.h#L212) where I fixed it in PR #326

**Comment by fmoessbauer** [comment]
Already fixed in PR #326
