### ISSUE TITLE
Getting te `dash::Team` for `const` containers

### ISSUE THREAD

**Issue by bertwesarg** [dash-project/dash#385]
It is currently not possible to work with a `dash::Team` if one only has a `const&` to a dash container. There is only:

https://github.com/dash-project/dash/blob/development/dash/include/dash/Matrix.h#L381

As having a `const&` to a `dash::Team` isn't that of a value anyway (can't be used to create new conteiner objects, as they require a non-const argument), I suggest to add only this:

```
  Team                      & team() const;
```

**Comment by bertwesarg** [comment]
Contrary to `dash::Matrix`, `dash::Array` has only the `const` variant for `team()`:

https://github.com/dash-project/dash/blob/development/dash/include/dash/Array.h#L1101

**Comment by fmoessbauer** [comment]
That should be consistent in both cases, but there are some limitation regarding constness, as the team is stored as reference:

- Each team carries an internal state, hence a const team cannot be modified
- If using `const Team &` in the container, a team gained from a container cannot be split

**Comment by bertwesarg** [comment]
Thats why my propsoal is `Team& team() const`. I did it already here:

https://github.com/bertwesarg/dash/commit/6dae20e2b0a959381b63b61c6f6ad94d71e358a3

**Comment by fmoessbauer** [comment]
Ah, got it. Please make a PR.

**Comment by bertwesarg** [comment]
Will do.
