### ISSUE TITLE
build: Check that the provided HDF5 has MPI support

### ISSUE THREAD

**Issue by bertwesarg** [dash-project/dash#388]
If the build env does provide an HDF5 lib, than this library does not necessarily have MPI support. But DASH does not perform a check in `cmake`, thus the build may fail at `make` time, which is cumbersome for a user.

**Comment by fmoessbauer** [comment]
That is not correct. If the version of CMake is recent enough, it is checked if the found version is the parallel one. However, for older versions it's not possible to check which version is found. If you have a (portable!) solution for that, please tell us.

Here is the check implemented: [CMakeExt/HDF5.cmake](https://github.com/dash-project/dash/blob/development/CMakeExt/HDF5.cmake#L29)

**Comment by bertwesarg** [comment]
Than increase the required CMake version! I find this rather lazy to rely on CMake to do such basic check. For HDF5, one would check if it `#define H5_HAVE_PARALLEL`, which should be trivial without relying on a specific CMake version.
