### ISSUE TITLE
RFC: flush-free async put/get using stream operators

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#390]
During a short discussion on our interface(s) for asynchronous transfer today, we agreed that an interface using `dash::Future` is desireable (and on the way in #371) and that we also want to have a nice C++'ish interface for transfers for which the user provides the buffer. Right now this is done using `dash::Array::async.get(T*)`, which is rather C-style. 

My proposal: use the stream operators on `dash::Array::async` to kick off a transfer and any `flush`/`barrier` on the container to wait for completion. Example:

```
int val;
dash::Array<int> array(N);
// fill array...

// kick-off transfer
array.async[0] >> val;
// do some computation

// wait for transfer to complete
// array.async.flush() or
array.flush();
// val can be used now
std::cout << val;
```

The streaming operators seem to be a good choice because the `istream` and `ostream` stream buffers are known concepts to users. In our case though, the variables cannot be re-used before the `flush()` operation but that is a matter of documentation, imo. In contrast to `dash::Future`, the overhead should be smaller as it does not require creating intermediate objects.

It's just an idea I wanted to put out for discussion (maybe it's floating around somewhere already?) and I am looking forward to your comments.

**Comment by dhinf** [comment]
Although i like the current syntax a tiny bit more, I would like to use the proposed one in future. We get rid of the pointer and i think it is more obvious to the user what happens.

**Comment by fuchsto** [comment]
Prettyfullness aside, using the stream operator for something that's not a stream is ... I'm sweating.

Seriously though, Is the operator precedence of `>>`, `<<` okay?
And you wrote it yourself: 

> The streaming operators seem to be a good choice because the istream and ostream stream buffers
> are known concepts to users.

Would be devious then if we would provide the operator ... but not stream semantics ... *pets white persian cat*

> In our case though, the variables cannot be re-used before the flush() operation but that is a matter
> of documentation

*insane laughter, raising steel fist prosthesis, persian cat runs away*

**Comment by devreal** [comment]
*Sigh*. Cynicism make discussions so much more fun. 

I regard these operators as a nice way of capturing the address of the target or source variable without having to poke around C-style pointers. But well, I agree that it's not exactly stream semantics... 

Maybe someone has a better idea. Until then, we will have to cope with ugly pointers (and no, I do not regard something like `async.get(T&)` as any better, I think it's even worse than clear pointer syntax).

**Comment by fuchsto** [comment]
No no! Sorry, I wasn't being cynical. Not intentionally, at least.
Just wanted to put this into formal perspective without resorting to formalese.

In brief: I agree, stream operators are well understood by users and the proposed interface is pretty. But we'd have to follow through. Exceptions from expected behavior are evil, especially when the interface looks so familiar.

So I'd like to resolve this by making it stream-compliant.

**Comment by fuchsto** [comment]
... and we actually might want range expressions here:

~~~c++
auto fut_expr = some_async | transform(multiplies (3.1415));
~~~

... because eliminating temporaries is exactly what they are good at. Just a thought.

**Comment by rkowalewski** [comment]
At the project meeting we have decided to omit the conversion of `dash::GlobAsyncRef<T>` to `T`. This should clarify the confusion of this issue while preserving a well-defined and consistent interface.

**Comment by devreal** [comment]
Closing this issue because it's not going anywhere. There are discussions about introducing a fence call in MPI RMA, which we hopefully use to avoid flushes after each and every put. However, we still need to work on a description of the memory model...
