### ISSUE TITLE
Fix multi-node copy operations

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#401]
`dash::copy` is broken for copy operations spanning more than the current node and its neighbors. 

Example:

```
dash::Array<int> arr(dash::size());
std::vector<int> vec(dash::size());

dash::copy(vec.begin(), vec.end(), arr.begin());
```
with `dash::size()` > 3.

Related: #386 for `dash::transform`

**Comment by fuchsto** [comment]
It's the local-to-global variants only, right? Global-to-local copying has been evaluated and benchmarked in lots of use cases, I would expect it's fine, Local-to-global has just been implemented for a single scenario and didn't get any love, yet.
And, yes, that's annoying ... as you wrote yesterday, it's crucial to document "restricted" implementations like this one

The n-dim ranges and views can solve the underlying partitioning problem. So I prioritize documentation of views first and then power-wash the algorithms section.

**Comment by devreal** [comment]
> It's the local-to-global variants only, right? Global-to-local copying has been evaluated and benchmarked in lots of use cases, I would expect it's fine, Local-to-global has just been implemented for a single scenario and didn't get any love, yet.

Yes, you're right. I seem to have missed the `while` loop in the global-to-local overload of `copy_impl` that iterates over the source units.

> The n-dim ranges and views can solve the underlying partitioning problem. So I prioritize documentation of views first and then power-wash the algorithms section.

Sounds good to me :+1:

**Comment by devreal** [comment]
Closing this as a duplicate of #346
