### ISSUE TITLE
Make build system Apple LLVM compatible

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#404]
Currently DASH cannot be compiled on Mac, which uses Apple LLVM version 8.1.0 (clang-802.0.42).

To make it compatible, the following has to be done:

- [x] Remove `fatal_error` in MPI.cmake if no MPI implementation is found and shmem is used
- [ ] Correct implementation of DART-shmem to meet the DART interface (at least minimal features without compiler error)
- [ ] Remove `has_trivial_copy_constructor` trait (is that even C++11?). Better use macro.
- [ ] Check features of SHMEM implementation in Cmake:
`shmem/include/dash/dart/shmem/shmem_barriers_if.h:7:10: fatal error: 'sys/eventfd.h' file not found
`

Let's discuss this at the meeting. Probably we decide not to support Apple LLVM, but that should be documented.

**Comment by devreal** [comment]
>  Remove fatal_error in MPI.cmake if no MPI implementation is found and shmem is used

That should be fixed in #403, right?

> Correct implementation of DART-shmem to meet the DART interface (at least minimal features without compiler error)

My feeling is that this is a bigger endeavor, although it would be nice to have, yes. 

In general: why do you need `shmem` to support Apple LLVM? Is there no MPI?

**Comment by fmoessbauer** [comment]
> That should be fixed in #403, right?

Yes, I guess. But as shmem is not working, I cannot verify this

> My feeling is that this is a bigger endeavor, although it would be nice to have, yes.

Yes, unfortunately... Would be something for a student project.

> In general: why do you need shmem to support Apple LLVM? Is there no MPI?

At least a short google search did not point me to any. OpenMPI is no solution as well because it requires a F77 compiler which is not available on mac.

**Comment by fuchsto** [comment]
*Affectionate look at PowerBook on shelf*

Hm. They have been so useful, back then.

**Comment by fmoessbauer** [comment]
Support is dropped, as there are not apple HPC systems which are our primary target.
