### ISSUE TITLE
dash::Array - not enough space allocated/accessible

### ISSUE THREAD

**Issue by BenjaProg** [dash-project/dash#432]
Hey DASH Team!
I noticed that dash::Array has a problem with large array sizes!
It either leads to an error when trying to allocate or it seems to successfully allocate and on element access you get an segfault!

Since i got the problem in winnow (one of my cowichan implementations) I didn't write a dedicated test program for time reasons.
I give my best to describe it thoroughly and wrote some scripts to execute and see the problem at first hand... 
The location of the files is in [this](https://github.com/dash-project/dash-apps/tree/bug-ArrayAllocation/cowichan/winnow) dedicated branch.

The code in question is in "winnow.h".
important note:
When executing one of the scripts you should get some output to stdout.
All these outputs are debug outputs for just this problem case.
That's why they aren't in any DEBUG clauses!
And for gods sake don't execute winnow with this large input without the "--is_bench" flag!
The IO will take forever ^^ (but first you will have to provide the right input anyway...)
Okay back to the problem:
If you execute "crash_withError.sh" an Array of the size 225000000 (elements! one element should be 12 bytes big) is needed and should fail to allocate at [here](https://github.com/dash-project/dash-apps/blob/9e99bb80425ef1a4f9440ca2de404d46b162b111/cowichan/winnow/winnow.h#L293). At least it does crash for me at project03.
And that's the message i get:
`Fatal error in MPI_Alloc_mem: Invalid argument, error stack:
MPI_Alloc_mem(129): MPI_Alloc_mem(size=-1594967296, MPI_INFO_NULL, baseptr=0x7ffec70879b8) failed
MPI_Alloc_mem(87).: Invalid value for size, must be non-negative but is -1594967296`
Curious that he gets negative values at some point...! That's not what it gets from me.

Next case, next script: "crash_withoutError.sh". Despite the space needed for the same Array is even bigger (1600000000 elements) no error is thrown [here](https://github.com/dash-project/dash-apps/blob/9e99bb80425ef1a4f9440ca2de404d46b162b111/cowichan/winnow/winnow.h#L293).
But the [memcpy](https://github.com/dash-project/dash-apps/blob/9e99bb80425ef1a4f9440ca2de404d46b162b111/cowichan/winnow/winnow.h#L497) fails.
The reason is that the access to the elements of "toSort" is limited somehow... there seems to be less space than requested!
For example i can access [toSort[437700264]](https://github.com/dash-project/dash-apps/blob/9e99bb80425ef1a4f9440ca2de404d46b162b111/cowichan/winnow/winnow.h#L485) but not [toSort[437700265]](https://github.com/dash-project/dash-apps/blob/bug-ArrayAllocation/cowichan/winnow/winnow.h#L488).
for readability:
1600000000 (number of elements that should be accessible) >
437700265.
In "noCrash.sh" the input (or the resulting allocation...) seems to be small enough that the error doesn't occur. 
In "noCrash2.sh" the same input as in "crash_withError.sh" is used, but with 2 units -> the allocation per unit is smaller!

I need it to work with one unit as well, because I want to measure the speedup.
Hopefully i didn't forget anything... please feel free to ask!
(Note: CSR-Pattern doesn't support size_t as indextype )

**Comment by devreal** [comment]
I will look into this. Three questions first:

1) Which MPI implementation + version are you using (I assume it's Open MPI but I don't trust my glass ball that much)
2) Which system are you running on? Is this your 32bit VM or a 64bit system?
3) Are shared memory windows enabled? I've had issues with large allocations of shared memory windows in the past so it might be worth trying without them.

**Comment by devreal** [comment]
OK, so this was one of those things... 

Please have a look at `bug-432-largearray` and PR #433. I was able to run your tests on one process on our cluster. There seems to another issue if I go to 4 processes, though. 

Please let me know if that helps.

**Comment by BenjaProg** [comment]
I was using `Intel(R) MPI Library for Linux* OS, Version 2017 Update 2 Build 20170125 (id: 16752)`
[That's the processor](http://ark.intel.com/products/64586/Intel-Xeon-Processor-E5-2630L-15M-Cache-2_00-GHz-7_20-GTs-Intel-QPI) of the university machine. 
That's the Linux Distribution and Version: `Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP`
-> 64Bit
Behaviour is the same with shared memory windows dis-/enabled.
Just tried it with `DENABLE_DEFAULT_INDEX_TYPE_LONG=ON` -> no difference
But in the progess of testing i noticed the error message is different with shared windows enabled:
`Fatal error in PMPI_Win_allocate_shared: Invalid size argument in RMA call, error stack:
PMPI_Win_allocate_shared(242): MPI_Win_allocate_shared(size=-1594967296, info=0x9c000000, comm=0x84000001, baseptr=0x7ffdea67aa48, win=0x7ffdea67aa3c) failed
PMPI_Win_allocate_shared(203): Invalid size argument in RMA call (value is -1594967296)`
But not that different. Just nice to see it's really using a different call.

I just ran some additional tests. The results are the same. Below the details!
The output contains my debug output as well.

Open MPI 1.10.4 SharedWindows=OFF | DEFAULT_INDEX_TYPE_LONG=OFF
------
<details><summary>./crash_withError.sh output:</summary>
[projekt03:29616] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_plm_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)

[projekt03:29616] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_ras_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)
should be 1 and is:1 ## how many elements should the array hold 225000000
[projekt03:29618] *** An error occurred in MPI_Alloc_mem
[projekt03:29618] *** reported by process [3824287745,0]
[projekt03:29618] *** on communicator MPI_COMM_WORLD
[projekt03:29618] *** MPI_ERR_ARG: invalid argument of some other kind
[projekt03:29618] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[projekt03:29618] ***    and potentially your MPI job)
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
Process name: [[58354,1],0]
  Exit code:    13
</details>

***
<details><summary>./crash_withoutError.sh output:</summary>
[projekt03:29678] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_plm_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)

[projekt03:29678] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_ras_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)
should be 1 and is:1 ## how many elements should the array hold 1600000000
toSort.size(): 1600000000
sizeof(size_t): 8
made it
made it2
lclOffset0
lclDest vs lbegin
0x7f5754043040
0x7f5754043040
1600000000, 12, 19200000000
1600000000, max:1537228672809129301
0x7f42cccc1040
0x7f474534d040
test element access...
[projekt03:29680] *** Process received signal ***
[projekt03:29680] Signal: Segmentation fault (11)
[projekt03:29680] Signal code: Invalid permissions (2)
[projekt03:29680] Failing at address: 0x7f588d158024
[projekt03:29680] [ 0] /lib64/libpthread.so.0(+0xf100)[0x7f589368f100]
[projekt03:29680] [ 1] /lib64/libc.so.6(+0x14ad57)[0x7f5893408d57]
[projekt03:29680] [ 2] ./winnow[0x42be58]
[projekt03:29680] [ 3] ./winnow[0x4094f2]
[projekt03:29680] [ 4] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f58932dfb15]
[projekt03:29680] [ 5] ./winnow[0x40a1bd]
[projekt03:29680] *** End of error message ***
mpirun noticed that process rank 0 with PID 29680 on node projekt03 exited on signal 11 (Segmentation fault).
</details>

***
<details><summary>the "noCrash*" executions led to the same behaviour like with intelMPI (works) except for the first two lines of output:</summary>
[projekt03:30002] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_plm_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)

[projekt03:30002] mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.4/lib/openmpi/mca_ras_tm: libpbs.so.0: cannot open shared object file: No such file or directory (ignored)
</details>

***
MPICH 3.2 SharedWindows=OFF | DEFAULT_INDEX_TYPE_LONG=OFF
------
<details><summary>./crash_withError.sh output:</summary>
should be 1 and is:1 ## how many elements should the array hold 225000000

Fatal error in MPI_Alloc_mem: Invalid argument, error stack:
MPI_Alloc_mem(117): MPI_Alloc_mem(size=-1594967296, MPI_INFO_NULL, baseptr=0x7ffcf1493f58) failed
MPI_Alloc_mem(80).: Invalid value for size, must be non-negative but is -1594967296
</details>

***
<details><summary>./crash_withoutError.sh output:</summary>
should be 1 and is:1 ## how many elements should the array hold 1600000000

toSort.size(): 1600000000
sizeof(size_t): 8
made it
made it2
lclOffset0
lclDest vs lbegin
0x7fe03e84d010
0x7fe03e84d010
1600000000, 12, 19200000000
1600000000, max:1537228672809129301
0x7fcbb6f88010
0x7fd02f614010
test element access...
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 32684 RUNNING AT projekt03
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
</details>

**Comment by ddiefenthaler** [comment]
Is this issue really resolved?
Otherwise reopen please.
