### ISSUE TITLE
dart_wait needs  double pointer for handle

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#435]
The function dart_wait only allows dart_handle_t as parameter. This works for freeing the memory but not for setting handle to NULL. Therefor we would need dart_handle_t * . As user i would expect that my handle becomes NULL after freeing memory. 
To fix this we have to change the dart interface and all calling functions (dart and dash).

In my opinion it is a mistake in the interface and should be changed. 
I would fix it, if no one proves me wrong.

**Comment by devreal** [comment]
You are right, I've been thinking about this as well. I wanted to merge #419 today so we can add this there before the merge (and proper review, of course)

**Comment by devreal** [comment]
Fixed through #419
