### ISSUE TITLE
Fix constness of containers

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#459]
While working on #458 I realized that access to DASH containers is not const-correct, i.e., a function can alter the elements of a container that's passed as const reference. Hence, the following example compiles fine although it shouldn't:

```
void foo(const dash::Array<int>& arr) {
  arr[0] = 0;
}
```

The reason is that `operator[](size_t) const` returns a `GlobRef<const T>` where imo that should be a `const GlobRef<T>`. `GlobRef` (and it's specializations) should be const-correct.

This has low priority, setting it for 0.4.0 for now.

**Comment by fuchsto** [comment]
Right, but on global references and const'ness, see https://github.com/dash-project/dash/pull/458#discussion_r149868238

**Comment by ddiefenthaler** [comment]
This issue has been fixed through #458 (see commit [8ef3690](https://github.com/dash-project/dash/pull/458/commits/8ef3690c549521c55e5b0a5be11fa2b9639171ca)).
