### ISSUE TITLE
Installing `dash-test-mpi` conflicts with `/bin/dash` shell

### ISSUE THREAD

**Issue by bertwesarg** [dash-project/dash#483]
The `dash-test-mpi` binary is installed into a `dash/test/mpi` subdirectory of the `bin` directory, though if one specifies `/bin` as this directory, it may overwrite/fail because of the existing `/bin/dash` shell. Having subdirectories in bin-directories is not very common any way. I think putting the binary into a `dash` subdirectory of `libexec` fits best.

**Comment by devreal** [comment]
The same problem seems to exist for the `examples` binaries. I wonder whether it makes sense to install them at all. If you want to run tests and examples you can run them from the build directory, right? Both examples and the test suite are not required for using DASH in an application...

**Comment by rkowalewski** [comment]
This is not an issue at all. This problem is something which may happen to any application and it is the user's responsibility to prevent these conflicts.

**Comment by bertwesarg** [comment]
And the reason to create directories in the `bin/` directory to begin with is as follows? Honestly, executables which you want to hide from the user (i.e., not in `bin/') should either be in `LIBEXECDIR` or under 'share'.

**Comment by fmoessbauer** [comment]
@bertwesarg: I missed that point, reopen the issue. IMO only lib dash should be installed and not the examples or tests.
