### ISSUE TITLE
Halo ignores some outside borders with Cycle::FIXED

### ISSUE THREAD

**Issue by knuedd** [dash-project/dash#487]
When I add a HaloMatrixWrapper to a 3D NArray with `Cycle::FIXED` then it ignores some outside halo areas in the `set_fixed_halos()` call. One can access those halo areas with no trouble via `halo_element_at()`, though.

You can reproduce and see this in dash-apps/multigrid/ when running `mpirun -n 4 multigrid3d -t`

Try adding the following lines of code to the end of the HaloMatrixWrapper constructor:

```
{
int b= 0;
int d= 0;
int n= 0;
for(const auto& region : _haloblock.boundary_regions()) {
      auto rel_dim = region.spec().relevant_dim() - 1;
      if(region.is_border_region() ){
         b++;
      }
      if(region.is_border_region() && region.border_dim(rel_dim) ){
         d++;
      }
      if(region.is_border_region() && region.border_dim(rel_dim)
         && _cycle_spec[rel_dim] == Cycle::FIXED) {

            n++;
    }
}
std::cerr << "unit " << dash::myid() << " has " << _haloblock.boundary_regions().size() << " halo regions, " << b << " border regions, " << d << " border dim, " << 
n << " FIXED" << std::endl;
}
```
... for the case with 4 units it will show that there are 23 border regions (correct) but only 22 with `region.border_dim(rel_dim)` and 22 with `_cycle_spec[rel_dim] == Cycle::FIXED`. Thus 1 is missing.

In the case with 8 units, 13 instead of 19, thus 6 missing. With 2 units it seems to be correct.

**Comment by dhinf** [comment]
Fixed in the feat-halo branch
