### ISSUE TITLE
make error, cannot find the dash libs.

### ISSUE THREAD

**Issue by siebeniris** [dash-project/dash#489]
Makefile:
MPICXX = mpicxx

DASH_ROOT = $(HOME)/opt

DASH_LIB = -L$(HOME)/opt/lib -libdash-mpi -libdart-mpi -libdart-base
DASH_INC = -I$(HOME)/opt/include

all: hello

hello : hello.cc
		$(MPICXX) -o hello $(DASH_INC) hello.cc $(DASH_LIB)

clean :
	    rm -f *~
	    rm -f ./hello

make ===>

mpicxx -o hello -I/home/xx/opt/include hello.cc -L/home/xx/opt/lib -libdash-mpi -libdart-mpi -libdart-base
/usr/bin/ld: cannot find -libdash-mpi
/usr/bin/ld: cannot find -libdart-mpi
/usr/bin/ld: cannot find -libdart-base
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'hello' failed
make: *** [hello] Error 1

Is this some kind of link broken?
Any advice to make it work?

**Comment by devreal** [comment]
Two things:
1) Can you please verify that the libraries are located in `~/opt/lib`? 
2) Instead of 
```
mpicxx -o hello -I/home/xx/opt/include hello.cc -L/home/xx/opt/lib -libdash-mpi -libdart-mpi -libdart-base
```
the link line should look like:
```
mpicxx -o hello -I/home/xx/opt/include hello.cc -L/home/xx/opt/lib -ldash-mpi -ldart-mpi -ldart-base
```
(notice the use of `-ldash-mpi` instead of `-libdash-mpi`)

DASH also comes with a compiler wrapper, called `dash-mpicxx`, which should set all the paths and link all required libraries.

**Comment by siebeniris** [comment]
Hi @devreal , thanks for replying.
Yeah , the libraries are in ~/opt/lib:
```
  ~/opt/lib  ls 
libdart-base.a  libdart-mpi.a  libdash-mpi.a
```
I changed to ldash-mpi instead of -libdash-mpi.
I think it is working, but it could not find the libdash.h , which I used in the example 1 from the tutorial [http://www.dash-project.org/tutorial/](url):
```
mpicxx -o hello -I/home/xx/include hello.cc -L/home/xx/lib -ldash-mpi -ldart-mpi -ldart-base
hello.cc:1:21: fatal error: libdash.h: No such file or directory
 #include "libdash.h"
                     ^
compilation terminated.
Makefile:11: recipe for target 'hello' failed
make: *** [hello] Error 1
```
However, libdash.h is in ~/opt/include.

**Comment by devreal** [comment]
> However, libdash.h is in ~/opt/include.

Try adding `-I$HOME/opt/include` to your command line (instead of `-I/home/xx/include`). 

I guess we need to adjust our examples...

**Comment by siebeniris** [comment]
@devreal  thanks !
Unfortunately , there is another error... And I don't really understand this error.. 
 make
```
mpicxx -o hello -I/home/xx/opt/include hello.cc -L/home/xx/opt/lib -ldash-mpi -ldart-mpi -ldart-base
/usr/bin/ld: /home/xx/opt/lib/libdart-base.a(host_topology.c.o): undefined reference to symbol 'hwloc_get_obj_by_depth'
//usr/lib/x86_64-linux-gnu/libhwloc.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'hello' failed
make: *** [hello] Error 1
```

**Comment by devreal** [comment]
The error indicates that DASH was built with support for `hwloc` enabled (you probably have it installed on your system). When you link your application you also have to link `libhwloc`, e.g., by adding `-lhwloc`. I strongly suggest you use `dash-mpicxx` as it takes care of all of the third-party libraries (there might also be `libnuma` missing, just in case...) You can inspect the required libraries by invoking `dash-mpicxx` with the parameter `--dash:verbose`, which will print the invocation of the underlying MPI compiler.
