### ISSUE TITLE
dash::Array initializer_list constructor initializes with wrong values

### ISSUE THREAD

**Issue by clemensmanert** [dash-project/dash#5]
The dash::Array constructor initializes the Array with the wrong values.
 Array(
    size_type                           nelem,
    std::initializer_list<value_type>   local_elements,
Team & team = dash::Team::All())

Example: A call with dash::Array(4, {1,2,3,4}) would result in a dash::Array with values {1,1,1,1}.

**Comment by fmoessbauer** [comment]
As discussed after the meeting on wednesday, this constructor has to be removed. Due to the "hidden" parallelism the result is not well defined (local indices vs global indices).

**Comment by clemensmanert** [comment]
I'd not remove that constructor. It is makes unit tests much easier to read and write. The hidden parallelism can be described perfectly well in the docu.

**Comment by fmoessbauer** [comment]
Ok, get it ;) So I recommend implementing it the following way:
- init list denotes global array values
- each unit writes local values only
- provide a good documentation with examples as the behavior is not trivial

**Comment by fuchsto** [comment]
Okay for me. The size constructor conceptually has the same ambiguity (whether size refers to global or local capacity), so that's not a strong argument anyways.
@clemensmanert : you want it, you code it!
Assign me for review once unit tests pass.

**Comment by fuerlinger** [comment]
Agreed. An initializer list for a dash::Array should specify the global list of element values, i.e., it should have global-view semantics. This is consistent with the rest of dash::Array and was an early design decision for the Array.

**Comment by fmoessbauer** [comment]
For different solutions see:
- fb90f1a159c2358f95c3486be52f173f79b68531, branch `bug-array-init-list` @fmoessbauer
- b0244ae1098a7a37792d84ffca200c1813934d0b, branch `bug-Array_constructor_initializer_list_5` @clemensmanert

**Comment by fuchsto** [comment]
@clemensmanert Fixed in #53 and merged to development.
The actual problem was a result of confusing semantics of `dash::GlobPtr`, see Doxygen comments in 
`dash/include/dash/GlobPtr.h`
