### ISSUE TITLE
Can't build dash with clang 5.0.1

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#505]
CMake finds the compiler but don't want to build anything:
- cmake version 3.10.2
- Arch linux
- clean checkout development
- ./build.minimal.sh

Output below:
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:12 (cmake_policy):
  The OLD behavior for policy CMP0007 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0003 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0004 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:24 (cmake_policy):
  The OLD behavior for policy CMP0016 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Loading environment configuration from /home/huenich/DASH/github/dash_dev/config/default.cmake
-- Performing Test HAVE_STD_TRIVIALLY_COPYABLE
-- Performing Test HAVE_STD_TRIVIALLY_COPYABLE - Success
-- Found MPI_C: /usr/lib/openmpi/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/openmpi/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for OMPI_MAJOR_VERSION
-- Looking for OMPI_MAJOR_VERSION - found
-- Detected MPI implementation: openmpi
-- Detected MPI C compiler: /usr/bin/mpicc
-- Searching for PAPI in path 
-- Could NOT find PAPI (missing: PAPI_LIBRARIES PAPI_INCLUDE_DIRS) 
-- Searching for hwloc library in path /usr
-- Found HWLOC: /usr/lib/libhwloc.so  
-- hwloc includes:  /usr/include
-- hwloc libraries: /usr/lib/libhwloc.so
-- Could NOT find LIKWID (missing: LIKWID_LIBRARIES LIKWID_INCLUDE_DIRS) 
-- Searching for NUMA library
-- Found NUMA: /usr/lib/libnuma.so  
-- NUMA includes:  /usr/include
-- NUMA libraries: /usr/lib/libnuma.so
-- Searching for IPM library in path 
-- Could NOT find IPM (missing: IPM_LIBRARIES IPM_INCLUDE_DIRS) 
-- Searching for Plasma library in path PLASMA_PREFIX-NOTFOUND
-- Could NOT find PLASMA (missing: PLASMA_INCLUDE_DIRS) 
-- Trying to find HDF5 using cmake package
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/libhdf5.so/usr/lib/libsz.so/usr/lib/libz.so/usr/lib/libdl.so/usr/lib/libm.so (found version "1.10.1")  
-- Found HDF5: /usr/lib/libhdf5.so/usr/lib/libsz.so/usr/lib/libz.so/usr/lib/libdl.so/usr/lib/libm.so  
-- Looking for H5_HAVE_PARALLEL
-- Looking for H5_HAVE_PARALLEL - found
-- HDF5 includes:   /usr/include
-- HDF5 libraries:  /usr/lib/libhdf5.so/usr/lib/libsz.so/usr/lib/libz.so/usr/lib/libdl.so/usr/lib/libm.so
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Looking for cblas_sgemm in /usr/lib/libblas.so
-- Looking for cblas_sgemm in /usr/lib/libblas.so - not found
-- No CBLAS Interface found, try manually
-- Found LIBCBLAS: /usr/lib/libcblas.so  
-- BLAS includes:  
-- BLAS libraries: /usr/lib/libcblas.so
-- LAPACK includes:  /usr/include/atlas
-- LAPACK libraries: /usr/lib/liblapack.so/usr/lib/libblas.so
-- Could NOT find SCALAPACK (missing: SCALAPACK_LIBRARIES SCALAPACK_INCLUDE_DIRS) 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- CC  flags          :   -mtune=native -march=native -mfpmath=sse NOTFOUND   -DDASH_ENABLE_ASSERTIONS -DDART_ENABLE_ASSERTIONS
-- CXX flags          :   -mtune=native -march=native -mfpmath=sse NOTFOUND   -DDASH_ENABLE_ASSERTIONS -DDART_ENABLE_ASSERTIONS
-- CC  flags (Debug)  : -g -O0 -DDASH_DEBUG -g
-- CXX flags (Debug)  : -g -O0 -DDASH_DEBUG -g
-- CC  flags (RelWDeb): -O2 -g -DNDEBUG -g
-- CXX flags (RelWDeb): -O2 -g -DNDEBUG -g
-- CC  flags (Release): -O3 -DNDEBUG  -Ofast -DDASH_RELEASE
-- CXX flags (Release): -O3 -DNDEBUG  -Ofast -DDASH_RELEASE
-- MPI include path:         /usr/include
-- MPI libraries:
--     /usr/lib/openmpi/libmpi.so
-- MPI link flags:
--    -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -pthread
-- DART additional compile flags:
--     -DDART
--     -DDART_MPI_IMPL_ID="openmpi"
--     -DDART_MPI_IMPL_IS_OPENMPI
--     -DDART_MPI_ENABLE_UNIFIED_MEMORY_MODEL
--     -DDART_MPI_DISABLE_SHARED_WINDOWS
--     -pthread
-- DART additional libraries:
--     rt
-- DASH additional compile flags:
--     -DDASH
--     -DDASH_ENABLE_UNIFIED_MEMORY_MODEL
--     -DDASH_ENABLE_TEST_LOGGING
--     -DDASH_HAVE_STD_TRIVIALLY_COPYABLE
--     -DDASH_ENV_HOST_SYSTEM_ID='default'
-- DASH additional libraries:
--     rt
--     pthread
-- Building DASH library    dash-mpi
-- DASH version 0.3.0
-- -----------------------------------------------------------
-- Install prefix:           (INSTALL_PREFIX)                 /home/huenich/opt/dash-0.3.0/
-- Build type:               (CMAKE_BUILD_TYPE)               Release
-- Generic build:            (BUILD_GENERIC)                  OFF
-- Build shared libraries:   (BUILD_SHARED_LIBS)              OFF
-- Build tests:              (BUILD_TESTS)                    OFF
-- Host system identifier:   (ENVIRONMENT_TYPE)               default
-- Strict compiler warnings: (ENABLE_DEV_COMPILER_WARNINGS)   OFF
-- Style compiler warnings:  (ENABLE_EXT_COMPILER_WARNINGS)   OFF
-- Link Time Optimization:   (ENABLE_LT_OPTIMIZATION)         OFF
-- Compiler reports:         (ENABLE_CC_REPORTS)              OFF
-- Compile time reduction:   (ENABLE_COMPTIME_RED)            OFF
-- Debug log messages:       (ENABLE_LOGGING)                 OFF
-- Trace log messages:       (ENABLE_TRACE_LOGGING)           OFF
-- DART log messages:        (ENABLE_DART_LOGGING)            OFF
-- Runtime assertions:       (ENABLE_ASSERTIONS)              ON
-- Unified RMA memory model: (ENABLE_UNIFIED_MEMORY_MODEL)    ON
-- MPI shared windows:       (ENABLE_SHARED_WINDOWS)          OFF
-- MPI dynamic windows:      (ENABLE_DYNAMIC_WINDOWS)         OFF
-- Enable multithreading:    (ENABLE_THREADSUPPORT)           OFF
-- Default index type long:  (ENABLE_DEFAULT_INDEX_TYPE_LONG) OFF
-- libnuma support:          (ENABLE_LIBNUMA)                 OFF
-- hwloc support:            (ENABLE_HWLOC)                   OFF
-- hwloc PCI support:        (ENABLE_HWLOC_PCI)               ON
-- PAPI support:             (ENABLE_PAPI)                    OFF
-- MKL support:              (ENABLE_MKL)                     OFF
-- BLAS support:             (ENABLE_BLAS)                    OFF
-- LAPACK support:           (ENABLE_LAPACK)                  OFF
-- ScaLAPACK support:        (ENABLE_SCALAPACK)               OFF
-- PLASMA support:           (ENABLE_PLASMA)                  OFF
-- HDF5 support:             (ENABLE_HDF5)                    OFF
-- Enabled DART backends:    (DART_IMPLEMENTATIONS)           mpi
-- C   compiler id:          Clang
-- C++ compiler id:          Clang
-- MPI implementation:       openmpi
-- PAPI                      disabled
-- MKL                       disabled
-- BLAS                      disabled
-- hwloc                     disabled
-- likwid                    disabled
-- LAPACK                    disabled
-- ScaLAPACK                 disabled
-- PLASMA                    disabled
-- HDF5                      disabled
-- libnuma                   disabled
-- googletest                disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/huenich/DASH/github/dash_dev/build

   To build using these settings, hit ENTER

Scanning dependencies of target dart-base
Scanning dependencies of target dash-mpi
[  1%] Building C object dart-impl/base/CMakeFiles/dart-base.dir/src/hwinfo.c.o
[  1%] Building C object dart-impl/base/CMakeFiles/dart-base.dir/src/internal/domain_locality.c.o
[  2%] Building C object dart-impl/base/CMakeFiles/dart-base.dir/src/array.c.o
clang-5.0: error: no such file or directory: 'NOTFOUND'
make[2]: *** [dart-impl/base/CMakeFiles/dart-base.dir/build.make:87: dart-impl/base/CMakeFiles/dart-base.dir/src/hwinfo.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang-5.0: error: no such file or directory: 'NOTFOUND'
make[2]: *** [dart-impl/base/CMakeFiles/dart-base.dir/build.make:63: dart-impl/base/CMakeFiles/dart-base.dir/src/array.c.o] Error 1
[  2%] Building CXX object dash/CMakeFiles/dash-mpi.dir/src/Init.cc.o
[  4%] Building CXX object dash/CMakeFiles/dash-mpi.dir/src/GlobPtr.cc.o
[  4%] Building CXX object dash/CMakeFiles/dash-mpi.dir/src/Distribution.cc.o
clang-5.0: error: no such file or directory: 'NOTFOUND'
make[2]: *** [dart-impl/base/CMakeFiles/dart-base.dir/build.make:111: dart-impl/base/CMakeFiles/dart-base.dir/src/internal/domain_locality.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: dart-impl/base/CMakeFiles/dart-base.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
clang-5.0clang-5.0: : errorerror: : no such file or directory: 'NOTFOUND'no such file or directory: 'NOTFOUND'

clang-5.0clang-5.0: : errorerror: : no such file or directory: 'NOTFOUND'no such file or directory: 'NOTFOUND'

[  5%] Building CXX object dash/CMakeFiles/dash-mpi.dir/src/Logging.cc.o
make[2]: *** [dash/CMakeFiles/dash-mpi.dir/build.make:111: dash/CMakeFiles/dash-mpi.dir/src/Init.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [dash/CMakeFiles/dash-mpi.dir/build.make:87: dash/CMakeFiles/dash-mpi.dir/src/GlobPtr.cc.o] Error 1
clang-5.0: error: no such file or directory: 'NOTFOUND'
clang-5.0: error: no such file or directory: 'NOTFOUND'
make[2]: *** [dash/CMakeFiles/dash-mpi.dir/build.make:63: dash/CMakeFiles/dash-mpi.dir/src/Distribution.cc.o] Error 1
clang-5.0: error: no such file or directory: 'NOTFOUND'
clang-5.0: error: no such file or directory: 'NOTFOUND'
make[2]: *** [dash/CMakeFiles/dash-mpi.dir/build.make:135: dash/CMakeFiles/dash-mpi.dir/src/Logging.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1000: dash/CMakeFiles/dash-mpi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by pascalj** [comment]
I cannot reproduce this error but I get some similar `NOTFOUND` paths on CMake 3.10.2, e.g. for `PLASMA_PREFIX`. My suspicion is that it has something to do with a changed `find_path` behavior. Previously it didn't set the variable to `PATH_PREFIX-NOTFOUND` but now (3.10) it does.

**Comment by dhinf** [comment]
The thing is, no source files are copied to "dash/CMakeFiles/dash-mpi.dir/src".

**Comment by dhinf** [comment]
works fine, thanks

**Comment by pascalj** [comment]
It seems culprit is `find_package(OpenMP)`. which sets the value of `OpenMP_CXX_FLAGS` to `NOTFOUND`. So installing libomp and/or using #506 should fix the problem. I'm not sure whether this is actually a bug in the OpenMP Cmake module...
