### ISSUE TITLE
Issue with using UnorderedMap

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#517]
To track a problem reported through the DASH ML: 
---

I'm trying to use UnorderedMap in DASH, but a simple program seems to compile, but seg fault:
 
```
    #include <libdash.h>
    #include <dash/UnorderedMap.h>

    int main(int argc, char **argv) {
      dash::init(&argc, &argv);
      dash::UnorderedMap <int, int> map;
      dash::finalize();
    }
```
 
Is the map not yet fully implemented, or am I doing something wrong?

---

I think we should look into that and fix it...

**Comment by fuchsto** [comment]
@devreal Exactly, @iminkov helped me to get it right, it's not in a PR yet. I will poke him.

**Comment by devreal** [comment]
What is the state of this? We had a second (same?) user report the same issue on the user ML and this issue is over a year old now :(
