### ISSUE TITLE
dash::sort() hangs for degenerate inputs

### ISSUE THREAD

**Issue by fuerlinger** [dash-project/dash#540]
When using `dash::sort()` with certain degenerate inputs, the sorting algorithm appears to hang. E.g., if a sufficient number of elements are set to the element type's maximal value. For example, running this program with 4 units hangs:

~~~
  dash::Array<int> arr(100);
  for( int i=0; i<arr.local.size(); i++ ) {
    arr.local[i] = i;
  }

  std::fill(arr.local.begin()+10, arr.local.end(),
	    std::numeric_limits<int>::max());
  
  dash::barrier();

  dash::sort(arr.begin(), arr.end() );
  dash::barrier();
~~~

My guess is that the partition-finding logic is tripped up by the extremal values.

**Comment by rkowalewski** [comment]
Thank you reporting. It should be fixed in #543 now.

**Comment by rkowalewski** [comment]
I was definitely too overhasty with my previous comment. I actually found another ugly integer overflow (the second one). Will be hopefully fixed soon.

**Comment by rkowalewski** [comment]
@fuerlinger You can check and review #543. Your nasty unit test should work now.

**Comment by rkowalewski** [comment]
closed and fixed
