### ISSUE TITLE
Efficient Min / Max Reduction in DART

### ISSUE THREAD

**Issue by rkowalewski** [dash-project/dash#548]
In a recent issue #543  we had some discussions about the most efficient way for min and max reduction for an array of values. Assume further that each unit already knows for whatever reason the local minimum and maximum and we want to obtain the global minimum and maximum. This is the case in `dash::sort` for example. There are couple of options:

- Simply call `dash::min_element` and `dash::max_element` to get corresponding values. This may be fine if the local ranges are not sorted and the user does not know already the local min and max values. However, it may be not be very efficient in this case as it does not assume any order of the elements.
- Allocate two `dash::Shared<dash::Atomic<value_t>>` variables (for min and max respectively). All units then apply min / max reduction with one-sided atomics and, finally, all units read again the shared variables  to obtain the values. See [this test](https://github.com/dash-project/dash/blob/development/dash/test/container/SharedTest.cc#L249) for an example. This approach requires at least 3 barriers (two for creating the `dash::Shared` variables and another one to synchronize the units before the final read).
- call `dart_allreduce` **twice** with the local min and max values to obtain the global min and max values. This approach requires two "barriers".
- call `dart_allreduce` **once** to simultaneously apply both min and max reduction. I have implemented a prototypical pure MPI approach, see below. This approach requires one "barrier".

The interesting question is performance, of course. Which strategy we use should be determined based on measurements. If someone has time and motivation to do that, take on that. This issue is to track the idea and for discussions, of course.

~~~
#include <mpi.h>
#include <assert.h>
#include <cstdio>

#include <array>
#include <utility>

template <class T>
void min_max_reduce(
    const void* lhs_, void* rhs_, int* len, MPI_Datatype*)
{
  const T* lhs    = static_cast<const T*>(lhs_);
  T*       rhs = static_cast<T*>(rhs_);

  assert(*len == 1);

  if (rhs[0] > lhs[0]) {
    rhs[0]       = lhs[0];
  }

  if (rhs[1] < lhs[1]) {
    rhs[1]       = lhs[1];
  }
}

int main() {
  using value_t = int;

  MPI_Init(NULL, NULL);
  MPI_Op min_max_op;

  int r, np;

  MPI_Comm_rank(MPI_COMM_WORLD, &r);
  MPI_Comm_size(MPI_COMM_WORLD, &np);

  auto ret = MPI_Op_create(
      reinterpret_cast<MPI_User_function*>(&(min_max_reduce<value_t>)),
      true,
      &min_max_op);

  assert(ret == MPI_SUCCESS);

  int lmin = r;
  int lmax = 1000000 - r;

  std::array<value_t, 2> in{lmin, lmax};
  std::array<value_t, 2> out{};

  MPI_Datatype type;

  ret = MPI_Type_contiguous(2, MPI_INT, &type);
  assert(ret == MPI_SUCCESS);

  ret = MPI_Type_commit(&type);
  assert(ret == MPI_SUCCESS);

  ret = MPI_Allreduce (&in, &out, 1, type, min_max_op, MPI_COMM_WORLD);
  assert(ret == MPI_SUCCESS);

  MPI_Op_free(&min_max_op);
  MPI_Type_free(&type);

  assert(out[0] == 0);
  assert(out[1] == 1000000);

  MPI_Finalize();

  return 0;
}

~~~

**Comment by dhinf** [comment]
Also,a dart counterpart of MPI_Iallreduce woulld be nice, especially in terms of performance.  The multigrid implementation of @knuedd is a valid use case for it.

**Comment by devreal** [comment]
Provided in #562
