### ISSUE TITLE
DART local memory allocation leads to segfault

### ISSUE THREAD

**Issue by rkowalewski** [dash-project/dash#549]
Problem: If we allocate locally on a unit which has different global and local unit ids (e.g., `dash::myid() == 2 && split_team.myid() == 0`), the team id handling is buggy in DART.

It is clear why that is the case. While allocating the local memory we set the global pointer to the **global** unit id based on `DART_TEAM_ALL` (see [here](https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_globmem.c#L132)). While retrieving the local memory address of the global pointer we lookup the **local** unit id (see [here](https://github.com/dash-project/dash/blob/development/dart-impl/mpi/src/dart_globmem.c#L42)). This of course leads to a local NULL pointer if global and local unit do not match.

So we should rely either only on local or global unit ids.

**Comment by devreal** [comment]
> Problem: If we allocate locally on a unit which has different global and local unit ids (e.g., dash::myid() == 2 && split_team.myid() == 0), the team id handling is buggy in DART.

It is not. Local allocations have no team attached so the dart_gptr carries a global unit ID. The test case in #550 is invalid as it assigns an ID from a random team to a gptr that should contain ~global unit IDs~ unit IDs from DART_TEAM_ALL. We have no way to check that in `dart_gptr_setunit`.

**Comment by fmoessbauer** [comment]
In my opinion the local unit id's should be just a index-set of the corresponding global ids. However for all operations which provide a team parameter, local id's have to be used.

For dart_gptr however only global id's should be used, as otherwise these pointers cannot be passed to another team (or memory accessed by another team).

The conversion should be implicitly done in DART.

**Comment by fmoessbauer** [comment]
... and as @devreal said: The unit-test is invalid.

**Comment by devreal** [comment]
>  The conversion should be implicitly done in DART.

We have to store the team ID in the gptr because allocations are linked to a team, otherwise segment IDs are not unique (only the combination of team_id+segement_id can be guaranteed to be unique). It is also invalid to pass gptr to units outside of the team that allocated the memory, they could not access the underlying window. So storing relative IDs in gptr is perfectly fine.

**Comment by rkowalewski** [comment]
Well the unit test is kind of invalid, right. It is more a workaround to manifest the error.

However, this is definitely a bug. From the practical perspective if we know that team unit id 0 allocates locally a global pointer and then explicitly sets the unit id of the global pointer again to 0, this should be an idempotent operation, right?! And it should never lead to an error.

EDIT: This unit test is of course not valid in the general case. However, exactly this scenario is valid because we always operate in the context of team unit id 0.

**Comment by devreal** [comment]
And it does not. If you allocate local memory on `dash::myid() ==  0` and then assign `0` to the gptr everything is fine. Similarly, if `dash::myid() == 1` and you assign `1` it is correct. You just cannot assign a unit ID from any team other than `DART_TEAM_ALL`.

**Comment by devreal** [comment]
To get a better idea of what you are trying to achieve: what are you trying to achieve? ;)

**Comment by rkowalewski** [comment]
> For dart_gptr however only global id's should be used, as otherwise these pointers cannot be passed to another team (or memory accessed by another team).

If that would be the case we can remove the teamid from the global pointer. ;) And there was a long discussion once why we need the teamid in the global pointer. Otherwise, we are limited to 2^16 units in DASH.

> And it does not. (...lead to an error)

Well it does, see the unit test and CI.

**Comment by devreal** [comment]
>> For dart_gptr however only global id's should be used, as otherwise these pointers cannot be passed to another team (or memory accessed by another team).

> It that would be the case we can remove the teamid from the global pointer. ;) And there was a long discussion once why we need the teamid in the global pointer. Otherwise, we are limited to 2^16 units in DASH.

I outlined the rationale above: the team ID is required to guarantee unique segment identifier so gptr can be passed among units of the *same team*. Since passing gptr to units outside of the time is invalid we can safely store relative unit IDs in gptr. 

>> And it does not. (...lead to an error)

>Well it does, see the unit test and CI.

If you can present a *valid* test case we can better understand what you are trying to achieve. The test case you created is invalid, for the reasons stated above.

**Comment by rkowalewski** [comment]
I understand your arguments. However, in my opinion it is a valid test case because:

- For me as a user it is not visible whether we operate on global or relative unit ids. I have no idea that one API call (`dart_memalloc`) operates internally on global ids and the other API call (`dart_gptr_getaddr`) operates on relative ids.
- For the reason mentioned before I know that I am unit id 0 and allocated locally a global pointer. So I decide again to set the unit id to 0 and nothing "should happen".
- If it is an erroneous call the interface should
  a) document that, and
  b) the runtime should return with an error code to tell me that I passed an invalid argument.

The bug actually manifested in another unit test (DARTLockTest.TeamLockUnlock) after some internal changes in `dash::Shared` as a result of #545. In `dash::Shared` we internally call `std::unitialized_fill` on the local address of the owner to initialize local memory. However the local address is always NULL as `GlobStaticMem` calls `dart_gptr_setunit` in `GlobStaticMem.update_lbegin()`.

**Comment by rkowalewski** [comment]
And the reason why `std::uninitialized_fill` does not crash is that both `lbegin` and `lend` are NULL, so the algorithm does not do anything. It is clear that this is a bug in `GlobStaticMem` of course because we internally always set the (global) unit id of the global pointer to the relative unit id of the memory instance. And `dash::Shared` operates never on the global address otherwise, only on the global pointer.

I found this bug and I am on the way to fix that. However, the inconsistency in DART bothered me as well.

**Comment by devreal** [comment]
Discussed at F2F: not valid with updated memory space concepts.
