### ISSUE TITLE
cmake error (LAPACK) 

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#551]
cmake version 3.10.3

Here the error message:
LAPACK was disabled in config

Error mesage:
A library with LAPACK API found.
CMake Error at CMakeExt/LAPACK.cmake:7 (check_library_exists):
  check_library_exists Macro invoked with incorrect arguments for macro
  named: CHECK_LIBRARY_EXISTS
Call Stack (most recent call first):
  CMakeLists.txt:152 (include)

**Comment by fmoessbauer** [comment]
This is already a know issue and there is a fix in the pipe (@rkowalewski ?). The actual issue is that cmake changed the number of arguments for that macro in version 3.5.

Not quite maintainer friendly...

**Comment by fmoessbauer** [comment]
Fixed in #552
