### ISSUE TITLE
Missing Online documentation 

### ISSUE THREAD

**Issue by fabian-jung** [dash-project/dash#568]
The link from the project README.md to the online documentation (http://doc.dash-project.org/) is broken. The displayed error page shows the following information:

"Happstack 7.4.5

Something went wrong here
Internal server error
Everything has stopped

The error was "gitit.log: commitBuffer: permission denied (Read-only file system)""

**Comment by fuerlinger** [comment]
Restarted the system and seems to be working again for now, thanks for reporting!
