### ISSUE TITLE
Locality Tests fail in minimal build target

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#66]
If no hardware locality lib is loaded, some hardware metrices are set to "-1". However the `DARTLocalityTest` checks that these values are greater 0. Maybe some other test failures of the minimal target are symptoms of that bug.

See this [example build](https://circleci.com/gh/dash-project/dash/228?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

`ul->hwinfo.max_threads = -1`

**Comment by fuchsto** [comment]
Ah, the tests might be incorrect then. It depends on the level of the interface whether "unknown" (`-1`) or default values are reported by the locality component.

The failing assertion is `(ul->hwinfo.min_threads) > 0`, that's as low-level as it can get, so returning `-1` is the correct behavior.

Will have a look at the logs.

Actually, there should be two DARTLocality-Test Suites defined for builds with and without locality features.

**Comment by fuchsto** [comment]
Fixed in PR #78
