### ISSUE TITLE
Halo for N-D array

### ISSUE THREAD

**Issue by Goon83** [dash-project/dash#672]
Hi DASH Community,
Just crossed this project and found it is very interesting. 
Want to know more about the status of Halo layer (ghost zone) support for a N-dimensional array.  I saw some sample code there, like the below. It actually uses a 2D wrapper for Halo layer of 2D array.   How about a general support for halo layer on an N-D array ?

https://github.com/dash-project/dash/blob/development/dash/examples/ex.11.halo-stencil/main.cpp

PS:  sorry that not sure where to ask this question and just throw here.

**Comment by Goon83** [comment]
After studying the code a while, it seems that DASH supports at most 2D array, not N-D array, right ?

**Comment by devreal** [comment]
@Goon83 The Halo abstraction supports arbitrary dimensions of the matrix, @dhinf went through great pains to make that work afaik. What dimensionality are you looking for?

The tests contain an example of using a 3D matrix: https://github.com/dash-project/dash/blob/development/dash/test/halo/HaloTest.cc#L445 

The interface stays the same. I'm not sure that we have higher dimensions available online. Maybe @dhinf can comment on that.

**Comment by dhinf** [comment]
Hi, the halo abstraction works for N-Dim. You only have to change the template parameters. Compare the example @devreal provided with the two dimensional one and you can see what changed. Which Dimension do you have in mind?

**Comment by Goon83** [comment]
Thanks @devreal and @dhinf for clarification. I will give the code a try and see what happens. Will post here about results once I finished. 

Which Dimension do you have in mind?
>  As the question said, I am looking for a general solution for any N-D array, although 1D/2D/3D halo exchange is most desirable.  Some background: we are working on a generic data analysis platform ArrayUDF for array-type data analysis. DASH seems to be an ideal layer as in memory cache.  https://crd.lbl.gov/assets/Uploads/hpdc02.pdf


BTW, I also experienced errors in installed DASH on Mac, same as https://github.com/dash-project/dash/issues/616.   Linux system works fine.   I understand that Mac is not HPC system which runs the final app. But, it is the development/debug platform for most HPC apps (as far as I know here in our organizations).  two-cents suggestions: having  a version working on Mac might not need too much efforts but it pays.
