### ISSUE TITLE
Stencil w/ radius greater than one

### ISSUE THREAD

**Issue by pauleonix** [dash-project/dash#678]
Hi, I am using DASH in a student project to benchmark its performance on a 3-dim Stencil going 4 elements in each direction. I would like to use the halo abstraction as in ex.11.halo-stencil, but I can't find documentation on these features (I know, it is in the development branch, so it is not to be expected.). Does the ```value_at()``` method of the boundary iterator work with this kind of stencil? And if yes, how do I know which index gives me a value from which radius (to apply different coefficients at different radiii)? When I looked in the headers, it seemed, as if there even where some implementation for directly giving the coefficients to the ```StencilSpec```, or sth along the lines. Is this a thing?

PS: I think in the ex.11.simple-stencil, the data to be used as output (w/ ```niter``` even) should be ```data_old```.

**Comment by dhinf** [comment]
Hi, sorry for the late response. Please have a look at the example ex.02.matrix.halo.heat_equation. It is more obvious what the halo wrapper does. The feature branch feat-halo also fixed the problem with slow iterators for the inner part. 

A coefficient can be set per stencil point. If none is given, a default value of 1.0 is used. When you build dash with documentation, you can find documentation for the halo wrapper. If you have questions or need examples how to use the halo wrapper,  feel free to ask.

**Comment by pauleonix** [comment]
I understand now, that I give the position of the elements in ```.value_at()``` by the order I define the stencil elements. 
If you could give me a minimal example of giving the coeffs to the stencil and tell me how/when they are applied after that, I guess I will manage to make use of the halo wrapper. 
There isn't any way to define the stencil w/o having to write down every single element, right? For my case it is 24 elements and therefore a bit cumbersome, but I guess it is worth it for how much less code I will have in the section where I loop over the boundaries.

**Comment by dhinf** [comment]
3-D stencil with partly self-defined coefficients. In case of a 3-dim stencil point you need four arguments for the constructor. The first one sets the coefficient and the next three the stencil point:
   
```c++
   using StencilSpec_t = StencilSpec<StencilP_t, 6>;
    StencilSpec_t stencil_spec(
       StencilP_t(0.2, -1,  0,  0), StencilP_t(0.4, 1, 0, 0),
       StencilP_t( 0, -1,  0), StencilP_t(0, 2, 0),
       StencilP_t( 0,  0, -1), StencilP_t(0, 0, 3));
    HaloSpec_t halo_spec(stencil_spec);

    EXPECT_EQ(stencil_spec[0].coefficient(), 0.2);
    EXPECT_EQ(stencil_spec[1].coefficient(), 0.4);
    EXPECT_EQ(stencil_spec[2].coefficient(), 1.0);
```

**Comment by dhinf** [comment]
> There isn't any way to define the stencil w/o having to write down every single element, right? 

Not at the moment.

**Comment by dhinf** [comment]
hit the wrong button and accidentally closed the issue

**Comment by pauleonix** [comment]
So there is no way to automatically apply the stencil with the coefficients, meaning that at the moment it is just for convenience if you have a very complicated set of coefficients? My coefficients just depend on the radius from the center. So storage-wise it doesn't make sense to save them this way if there is not more to it.

**Comment by pauleonix** [comment]
I also have a very basic question. When using the global view of an DASH data structure to access single elements stored on a different node, like in ex.11.simple-stencil, does this mean, that internally there will be a single MPI call for each element? This would make for very bad performance, right?

**Comment by theGidy** [comment]
> I also have a very basic question. When using the global view of an DASH data structure to access single elements stored on a different node, like in ex.11.simple-stencil, does this mean, that internally there will be a single MPI call for each element? This would make for very bad performance, right?

From the point of a  user, I suppose that's true. I was not able to achieve a good performance while using large stencils on large arrays with this approach. In the end, I copied the data+halo with `dash::copy` to a local buffer and executed the stencil calculation on the buffer. But this resulted in other issues in the performance depending on the choosen pattern for the array on my local system. On the SuperMUC-NG to performance was ok with the copy approach.

**Comment by dhinf** [comment]
> So storage-wise it doesn't make sense to save them this way if there is not more to it.

The StencilOperator provides a method that uses the coefficients (set_ and get_value_at). But at the moment, if you know your coefficients use them plain in your stencil operation.

**Comment by dhinf** [comment]
> I also have a very basic question. When using the global view of an DASH data structure to access single elements stored on a different node, like in ex.11.simple-stencil, does this mean, that internally there will be a single MPI call for each element? This would make for very bad performance, right?

True, if you use global iterators the performance isn't bad, it's awful.  That's why the Halo wrapper manages the halo areas for you and also allows to update them within one call. The stencil operator provides proxy operators for the inner part of you sub matrix (no halo elements) and a boundary operator, where each element has at least on halo element. Normally you start the halo update asynchronously and calculate the inner part. After finishing the inner calculation and the halo update you start the boundary calculation. Here you achieve way better performance.

**Comment by dhinf** [comment]
Have a look at the example ex.02.matrix.halo.heat_equation. This example shows how to use the halo wrapper. Also, if your are using the branch feat-halo, the part marked slow in the example performs quite well now.

**Comment by pauleonix** [comment]
Some of the nodes I work on have a knl architecture with many slow cores. Is there any multithreading involved in ```ex.02.matrix.halo.heat_equation```? Or is it possible to speed up at least the inner part with an omp pragma?

EDIT: I should mention that my openMPI implementation doesn't allow for MPI_THREAD_MULTIPLE. Therefore I build DASH with ```-DENABLE_THREADSUPPORT=OFF```.

**Comment by dhinf** [comment]
sure, you can use OpenMP. We tested the halowrapper with OpenMP and with the DASH Tasking Model. You can use OpenMP For-Loops for the inner part and OpenMP tasking for the boundaries.

**Comment by pauleonix** [comment]
What is the reasoning behind using tasking here?

**Comment by dhinf** [comment]
you can separate the boundary regions. E.g. one task for north, one for south etc.

**Comment by pauleonix** [comment]
But that would give me only 6 tasks? And I don't see how this works with the iterators.

**Comment by devreal** [comment]
> But that would give me only 6 tasks?

You can use taskloops inside these tasks to generate more work (if the boundaries are big enough, that is).

**Comment by pauleonix** [comment]
So assuming the inner and boundary iterators work with openmp > 3.0 (I have 4.5) and that during the loops over these iterators there is no communication going on through MPI: 
In my use-case (stencil of radius 4, smallest global grid is 32^3, biggest is 512^3, between 4 and 16 dash processes) the boundary regions are very big. If that were not the case I would understand that having a lot of parallelization on the boundary might worsen the performance due to openmp overhead. I also understand, that due to data locality it might be a good idea to explicitly go through the different directions of boundaries. 
- Is the order in which the normal boundary iterator processes the boundary elements that bad (eg jumping between directions)?
- Is there more reasons than the ones I mentioned to use tasks, or could it be that in my case it works to just do an omp for loop over the complete boundary? (Another path might be to sequentially have a omp for loop for every boundary direction.)
- If I have to explicitly go over each direction a boundary could sit at, how do I get the iterators for these?

**Comment by pauleonix** [comment]
The version with 8 threads seems to be slower than a version with 8 processes. Could it be that the reason is that dash automatically uses MPI windows or even pthreads on a shared memory node and this is in some way better optimized here? 
Also it should be noted somewhere that without ```--bind-by none``` openmp regions are potentially being serialized :sweat_smile:

**Comment by dhinf** [comment]
> The version with 8 threads seems to be slower than a version with 8 processes

It can happen that you have indirct blocking with distributed processes (2x2x2 for 3d or 4x2 for 2d). But when you use one process only and 8 threads you need explicit loop blocking to use the cache optimal. Also you might need to consider the first touch policy -> depending on your numa domains

**Comment by dhinf** [comment]
>     * Is the order in which the normal boundary iterator processes the boundary elements that bad (eg jumping between directions)

The order is region wise. e.g. for full stencil in 2d the iterator follows the region numbers for the boundary. the iterator iterates over all elements of region and than goes to the next region
| 0 |        1      | 2 |
| 3 |     inner   | 4 |
| 5 |        6      | 7 |



>     * If I have to explicitly go over each direction a boundary could sit at, how do I get the iterators for these?

the method  iterator_at(region_index_t index) returns a pair with the begin and end iterator of the boundary for a specific region. 
The method can be called like this:
stencil_op.boundary.iterator_at(0) // for region 0, in 2D its north west
