### ISSUE TITLE
Is building with -DBUILD_GENERIC=ON a good idea?

### ISSUE THREAD

**Issue by pauleonix** [dash-project/dash#683]
How bad (performance-wise) is it to build DASH with the generic flag turned on? 

I have two kinds of nodes available, some with knl architecture and some with skylake architecture. I have to benchmark some DASH functionalities on both of them. Up until now I build DASH generically for it to work on both and then build two versions of my benchmark where I specified the architecture. 

Should I build two different versions of DASH, or is the difference in performance negligible?

**Comment by devreal** [comment]
Most of the pre-compiled (non-header) part of DASH is a simple wrapper around MPI functionality so I don't expect there to be a huge difference. It does depend on your application though: if you do plenty of small-size global memory accesses (i.e., plenty of calls into the runtime and MPI) you may see a difference as the generic compilation drops support for all of the fancy instructions modern processors offer. Building for both architectures gets you on the safe side ;)
