### ISSUE TITLE
some examples in "root/dash/examples" don't build

### ISSUE THREAD

**Issue by BenjaProg** [dash-project/dash#69]
The array examples series don't build in my VM on development branch.
In contrast ex.01.hello for example does build.
When I execute "build.sh" they are build successfully and are found in the folders:
"root/build/bin" and "root/build/dash".

When I try building the examples after building DASH with make in the folder "root/dash/examples/.."
I get an error. The outut of my building ex.02.array attempt is in the attachment.

[ex.02.array make log.txt](https://github.com/dash-project/dash/files/573937/ex.02.array.make.log.txt)

**Comment by fuerlinger** [comment]
These are two different build systems. When you run build.sh you use the CMake build system and it sounds like this works fine for you and builds all examples.

The Makefile in root/dash/examples/ is part of a separate manual build system (manually maintained configuration and make files for certain use cases) and the two systems don't mix.

**Comment by BenjaProg** [comment]
Yeah building with cmake seems to build all examples just fine.
@fmoessbauer said it might be a linker problem.
Unfortunately I don't understand the error message right now to resolve this issue.

**Comment by fuerlinger** [comment]
If cmake works fine, then there is really nothing to resolve. As I mentioned, the two build systems are not meant to work together.
