### ISSUE TITLE
MPI versions of travis ci do not support MPI3

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#7]
Hi Team!

unfortunately, no travis build environment currently supports packages for MPI3 [1]. Hence our CI scripts will fail as we depend on MPI3 [2]. Compiling a current version of MPI inside the travis env is not a possibility, as the compilation time reaches hours.
The recommended workaround for this problem is to use a docker container [3].

How should we proceed?
### References
- [1] https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
- [2] [Build Output](https://api.travis-ci.org/jobs/167636146/log.txt?deansi=true)
- [3] https://github.com/travis-ci/travis-ci/issues/5821

**Comment by fuchsto** [comment]
Oh. I assumed that, being Ubuntu 14.04 Server, it should support all of its deb packages.
Is there a specific reason why MPI-3 is not supported? Could it be fixed by adding an apt-source?

Integration tests pass on projekt03 for me, so it's a bummer.
Yes, sure, let's give docker a try if it doesn't work the usual way.

**Comment by fuchsto** [comment]
Are you sure about the missing MPI-3 support?
Log says:

```
Get:6 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/universe libopenmpi1.6 amd64 1.6.5-8 [1,396 kB]
Get:7 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/universe libopenmpi-dev amd64 1.6.5-8 [379 kB]
```

OpenMPI-1.6 implements MPI-3.x, and no host restrictions should apply.

Edit: Also see [this note in the Travis docs](https://docs.travis-ci.com/user/languages/c):

> The default environment variable $CC is known to interfere with MPI projects.
> In this case, we recommend unsetting it:

``` yaml
before_install:
  - test -n $CC && unset CC
```

**Comment by fmoessbauer** [comment]
Ok, I assumed that because some features seem to be missing, as the build script reported the mpi libs correctly:

```
MPI include path:         /usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI libraries:
--     /usr/lib/openmpi/lib/libmpi.so
--     /usr/lib/x86_64-linux-gnu/libdl.so
--     /usr/lib/x86_64-linux-gnu/libhwloc.so
```

```
/home/travis/build/fmoessbauer/dash/dart-impl/mpi/src/dart_team_group.c:535:5: warning: implicit declaration of function â€˜MPI_Win_create_dynamicâ€™ [-Wimplicit-function-declaration]
     MPI_Win_create_dynamic(MPI_INFO_NULL, subcomm, &win);
     ^
/home/travis/build/fmoessbauer/dash/dart-impl/mpi/src/dart_team_group.c:599:5: warning: implicit declaration of function â€˜MPI_Comm_split_typeâ€™ [-Wimplicit-function-declaration]
     MPI_Comm_split_type(
     ^
/home/travis/build/fmoessbauer/dash/dart-impl/mpi/src/dart_team_group.c:601:7: error: â€˜MPI_COMM_TYPE_SHAREDâ€™ undeclared (first use in this function)
       MPI_COMM_TYPE_SHARED,
```

I fixed the env variable (forgot to pull request ...) but unfortunately that did not solve the problem.

**Comment by fuchsto** [comment]
Implicit declarations suggest that these are missing in the MPI header that has been successfully included.
And that's because you were right, I confused the version numbers. Actually, openmpi-1.6 is ancient.

Well, we could check if an apt-source is provided somewhere for libopenmpi**2**-dev.
There is also libmpich2-dev, but it doesn't sport MPI-3 either.

Just switch to a docker environment if it's too much pain.

And yes, we could show dart-shmem some love and make it comply to current dart-if to use it as a fallback. But we will soon integrate IPM and nastyMPI, so that's not an option.

Also, we actually should have no conflicts with `$CC` as I don't use `mpicc` in CMake. 
MPI compile commands are composed manually to give us more control and to avoid exactly these situations.

**Comment by fmoessbauer** [comment]
I have already searched for a mpi ppa but did not find any. I would definitely recommend to switch to docker as we will have problems with other missing packages. Furthermore we can pre build all dependencies inside the docker container and just pull it.

I will check the workload... If anyone is interested in building the container, read this: https://docs.travis-ci.com/user/docker/.

**Comment by clemensmanert** [comment]
I don't think docker is a proper choice for a container system. I'd prefer Linux containers or Bsd Jails.

**Comment by fuchsto** [comment]
Yeah, we know, but Travis doesn't provide us with that option, and: who fixeth, ruleth!

@fmoessbauer Remember to use libopenmpi2-dev, libopenmpi-dev-1.10.x still only is MPI-2.

https://blueprints.launchpad.net/ubuntu/xenial/amd64/libopenmpi-dev/1.10.2-3

**Comment by fuchsto** [comment]
I sure don't know what's wrong about your Travis / Docker config, but I had to get some popcorn to watch the log roll down. The suspense is killing me.

Edit: Maybe try using absolute paths for logs, `pwd` might change between the stages.

**Comment by fmoessbauer** [comment]
Nice to hear that you are enjoying my helpless tries to get the job done :+1: HPC is just not made for customer ppa packages... 

Up to now the status is as follows:
- docker container is working
- papi is incompatible
- blas is incompatible
- travis does not show the error messages (no matter how hard I try)

**Comment by fmoessbauer** [comment]
After a hell of trying and hacking, **I got it finally working**. However the ticket should not be closed, as papi and blas have to be tested as well.

Another point is that not all failed tests are reported as such. When looking in the debug output there seem to be failed tests, but the dash-ci.sh script does not detect them.

@clemensmanert Please add the appropriate packages to the dockerfile and build papi directly from the sources.

**Comment by fuchsto** [comment]
Wow, would never have thought we'd have  a travis build within 24 hours of the migration.
Thank you, Felix! This was **so** needed.

But! Ha! Not quite there yet! It's not actually running the tests, is it? Looks like it aborts (without error code) because mpirun is run as root.

**Comment by fmoessbauer** [comment]
Yes Sir, but already fixed!

**Comment by fuchsto** [comment]
You are using the unholy `allow-run-as-root`?
I admire your courage, but ... https://www.youtube.com/watch?v=EWCGJaYk-Zw

I will figure out user modes for `mpirun`, we will keep fingers crossed until then.
Thank you for biting through config hell, it was well worth the effort.

**Comment by fmoessbauer** [comment]
I had similar thoughts, but in my opinion it's the easiest solution as the docker container only has a root user. Furthermore the flag only has effect if the user is stupid enough to call `sudo mpirun`.

Maybe we should enable this only if the ci script is started with `--enable-with-sudo`

**Comment by fuchsto** [comment]
Agreed, but there should be some way to restrict permissions for the MPI run.
Call it a day!

**Comment by fuchsto** [comment]
Closed the ticket as PAPI and BLAS do not enable major functions in DASH apart from `dash::summa` which is a too peculiar detail in the context of this issue request.
The most important optional dependency is hwloc which works just fine.
