### ISSUE TITLE
CopyTests fail in minimal build target

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#70]
If building the dash minimal target, dash::copy is not working properly. This can also be reproduced on a non virtualized / CI environment.

- [ ] CopyTest.AsyncGlobalToLocalBlock

```
/opt/dash/dash/test/CopyTest.cc:764
      Expected: num_elem_per_unit
      Which is: 20
To be equal to: dest_end.get() - local_copy
      Which is: 0
Unit 0
```

See [this build](https://circleci.com/gh/dash-project/dash/235) for details

**Comment by fuchsto** [comment]
Fixed in PR #79
