### ISSUE TITLE
Question: Dart Run Time SHMEM

### ISSUE THREAD

**Issue by arewedancer** [dash-project/dash#701]
Hi,
  Is SHMEM Dart run-time still contributor only? Is it going to be released to the general public?  If so, when is the SHMEM build going to be available? Thanks!

**Comment by devreal** [comment]
Hi @arewedancer 

> Is SHMEM Dart run-time still contributor only? 

What do you mean with "contributor-only"? And do you refer to the backend available in https://github.com/dash-project/dash/tree/development/dart-impl/shmem? That one unfortunately is not really maintained.

**Comment by arewedancer** [comment]
@devreal  It is stated in the README.md that
- SHMEM: Symmetric Hierarchical Memory access (contributor distribution
    only)
When I built dash 4.0 with -DDART_IMPLEMENTATIONS=shmem, it failed with errors

**Comment by devreal** [comment]
Interesting, I was not aware of that. @fuerlinger any hints?

AFAIK, we do not have a port to SHMEM. Currently the only fully supported implementation is the MPI-RMA backend.

**Comment by arewedancer** [comment]
@devreal  That's OK. Thanks for confirming this. By the way, with the MPI backend, does Dash mitigate against machine/node failures, or it relies on MPI implementations in case of failures?

**Comment by devreal** [comment]
There is no failure mitigation at this point. I guess the best bet is to write snapshots using the HDF5 backend and then restore from that in case of a failure.

**Comment by arewedancer** [comment]
Thanks! Closing this issue now.
