### ISSUE TITLE
Document CI procedure in DASH distribution docs

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#76]
To enable other contributors to extend the continuous integration builds, the current CI procedure should be explained in the DASH distribution docs (`/doc/CI/...`).

CI documentation should be comprehensible to an audience without prior experience in container configurations and summarize the relevant aspects from Travis/CircleCI documentation by example.

**Comment by fmoessbauer** [comment]
After a few days of recovery I am back again. I definitely agree that CI documentation is a priority task. Started documentation in branch `sup-76-cidoc`.

**Comment by fmoessbauer** [comment]
Please have a look at PR #84.

**Comment by fuchsto** [comment]
@devreal Let us know if the documentation of the CI procedures is okay for you:

https://dash.readthedocs.io/en/latest/CI/

**Comment by devreal** [comment]
Documentation looks good to me, thanks for the quick write-up. I used it while dealing with #93 and found it very useful. I just noticed an opened TODO that should be closed before closing this issue.

**Comment by fmoessbauer** [comment]
Ok great. Added description for last missing todo.

**Comment by devreal** [comment]
Great, thanks a lot! In case anything is unclear later I will open another ticket.
