### ISSUE TITLE
Re-consolidate CI tasks in CircleCI

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#87]
Each task (line) in the `circleci.yml` file adds an implicit barrier to the parallel execution of the containers.
As the trend in DASH CI is towards a subset of targets executed in each environment, this massively rises CI time.

For example the valgrind check is run if and only if the container is `openmpi2_vg` and build type is `debug`. All other containers do not even run the debug target.

Yes, I know the output is much more pretty if one target per line is set, but this can also be accomplished by copying the logs to the artifacts directory.

We should discuss this.

**Comment by fuchsto** [comment]
@fmoessbauer Yeah, I know ... It's painfully obvious when you look at the build timeline provided by CircleCI at the end of a build.

The actual reason for the "multistep-tasks" was to generate output within the 10-minute-mark.
What I also don't like is that for CircleCI, the build targets are defined in three places (pull, build and run scripts).

So yes, we should clean this up. Suggestions?

**Comment by fmoessbauer** [comment]
Our main problem is that we try to pass the configuration through multiple layers of CI, bash, docker and CI again...

However CI becomes to an full time job if we want to test the code automatically up to this detail. There are already four open tickes concerning CI and many of them are not trivial...

Why do we hit the time limit? If every step produces continuously output there should be no problem.

**Comment by fuchsto** [comment]
Naah, the CI setup has been eating up enough time already, and we should be satisfied with our workflow as it is.
In the beginning, all we wanted was Travis. Now our workflow looks like a mechanism from Koyaanisqatsi.

Roger will check if nastyMPI is integrated correctly some time after he is back, and for now we just clean up the scripts and focus on more interesting stuff.
Actually there is just valgrind and performance reports missing, I'm okay with executing them manually for the time being.

I fixed a bunch of bugs yesterday and today, now we have 4 unresolved defects left.
We should prioritize those and then complete features for the 0.3.0 release.

So: no additional features, just cleanup and documentation.

**Comment by fuchsto** [comment]
@fmoessbauer 
Build timing on CircleCI looks okay actually:
https://circleci.com/gh/dash-project/dash/317#build-timing/containers/0
So I think we can keep the current setup where CI tests are called separately to produce nicer log output.

**Comment by fmoessbauer** [comment]
Yes, that's ok for me. I added to copy the logs in the artifacts dir. This makes things much more comfortable when accessing them.

**Comment by fuchsto** [comment]
@fmoessbauer 
Test artifacts on CircleCI currently have test reports split into 3 XML files:

```
 Container 0
 '- $CIRCLE_TEST_REPORTS/
    '- mpich/
       '- Minimal/
          | -dash-tests-1.xml
          |- dash-tests-2.xml
          |- dash-tests-3.xml
          '- logs/
             |- build.log
             '- test_mpi.log
```

(see https://circleci.com/gh/dash-project/dash/342#artifacts/containers/0)

Why? The tests shouldn't be run on three containers, should they?

**Comment by fmoessbauer** [comment]
This is pure coincidence, the number actualy denotes the number of mpi processes. The xml files are automatically generated by googletest. So in each Container (aka environment) each build target is run with 1,2,3 mpi processes. This is also documented in the new CI doc ;)

**Comment by fuchsto** [comment]
Aah, understood. Apart from that, the test artifacts (test summary in XML) are broken once in a while when
test results of MPI processes are merged. But let's just not care, please.
