### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#97]
Some metric tonnes of features and bug fixes have been added since dash-0.2.0.
It's already hard to keep track, we have to update the CHANGELOG now and then to document our progress.

Also, there are some known limitations in the upcoming version 0.3.0 that must be documented in CHANGELOG before release.
The related issues are tagged as `known-limitation:0.3.0`:

<https://github.com/dash-project/dash/labels/known-limitation%3A0.3.0>

**Comment by devreal** [comment]
Do we have a branch for that? From my side, I could only mention tons of stability fixes :)

**Comment by fuchsto** [comment]
Well, _actually_ a dedicated branch should not be required.
Some time ago I stepped on a soap box and proclaimed that 

> Henceforth, all feature branches shall extend the change log before a pull request.

I did not even come close to care about this guideline ever again of course.
Will create branch `sup-97-maintainer-docs` for now, but let's remember to update the changelog before creating
pull requests in the future.

**Comment by fuchsto** [comment]
To automatically generate an unrevised change log from git history:

~~~sh
$ git log dash-0.2.0...42c48e6 \
    --pretty=format:'- [view commit](http://github.com/dash-project/dash/commit/%H) %s ' \
    --reverse
~~~

**Comment by fuchsto** [comment]
@dash-project/developers With the annual symposium meeting end of March, I think it's time to wrap up the release of DASH version 0.3.0. Please review your contributions and extend CHANGELOG in branch 
`sup-97-maintainer-docs`.

**Comment by devreal** [comment]
I think from the DART side everything is covered (but I will check once again). I assume we do the release after the meeting?

**Comment by fuchsto** [comment]
Yes, that's the general idea.
